<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/acl/policy_service.proto

namespace Eolymp\Acl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.acl.UpdatePolicyInput</code>
 */
class UpdatePolicyInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .eolymp.acl.UpdatePolicyInput.Patch patch = 10;</code>
     */
    private $patch;
    /**
     * Generated from protobuf field <code>string policy_id = 1;</code>
     */
    protected $policy_id = '';
    /**
     * Generated from protobuf field <code>.eolymp.acl.Policy policy = 2;</code>
     */
    protected $policy = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $patch
     *     @type string $policy_id
     *     @type \Eolymp\Acl\Policy $policy
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Acl\PolicyService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.acl.UpdatePolicyInput.Patch patch = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPatch()
    {
        return $this->patch;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.acl.UpdatePolicyInput.Patch patch = 10;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPatch($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Eolymp\Acl\UpdatePolicyInput\Patch::class);
        $this->patch = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string policy_id = 1;</code>
     * @return string
     */
    public function getPolicyId()
    {
        return $this->policy_id;
    }

    /**
     * Generated from protobuf field <code>string policy_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPolicyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->policy_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.acl.Policy policy = 2;</code>
     * @return \Eolymp\Acl\Policy|null
     */
    public function getPolicy()
    {
        return $this->policy;
    }

    public function hasPolicy()
    {
        return isset($this->policy);
    }

    public function clearPolicy()
    {
        unset($this->policy);
    }

    /**
     * Generated from protobuf field <code>.eolymp.acl.Policy policy = 2;</code>
     * @param \Eolymp\Acl\Policy $var
     * @return $this
     */
    public function setPolicy($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Acl\Policy::class);
        $this->policy = $var;

        return $this;
    }

}

