<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/cognito/user_service.proto

namespace Eolymp\Cognito;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.cognito.CreateUserInput</code>
 */
class CreateUserInput extends \Google\Protobuf\Internal\Message
{
    /**
     * username
     *
     * Generated from protobuf field <code>string username = 1;</code>
     */
    protected $username = '';
    /**
     * full name
     *
     * Generated from protobuf field <code>string full_name = 2;</code>
     */
    protected $full_name = '';
    /**
     * email
     *
     * Generated from protobuf field <code>string email = 3;</code>
     */
    protected $email = '';
    /**
     * password
     *
     * Generated from protobuf field <code>string password = 4;</code>
     */
    protected $password = '';
    /**
     * country
     *
     * Generated from protobuf field <code>string country = 5;</code>
     */
    protected $country = '';
    /**
     * birthday in format YYYY-MM-DD
     *
     * Generated from protobuf field <code>string birthday = 6;</code>
     */
    protected $birthday = '';
    /**
     * captcha challenge
     *
     * Generated from protobuf field <code>string captcha = 10;</code>
     */
    protected $captcha = '';
    /**
     * default locale for user
     *
     * Generated from protobuf field <code>string locale = 20;</code>
     */
    protected $locale = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $username
     *           username
     *     @type string $full_name
     *           full name
     *     @type string $email
     *           email
     *     @type string $password
     *           password
     *     @type string $country
     *           country
     *     @type string $birthday
     *           birthday in format YYYY-MM-DD
     *     @type string $captcha
     *           captcha challenge
     *     @type string $locale
     *           default locale for user
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Cognito\UserService::initOnce();
        parent::__construct($data);
    }

    /**
     * username
     *
     * Generated from protobuf field <code>string username = 1;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * username
     *
     * Generated from protobuf field <code>string username = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * full name
     *
     * Generated from protobuf field <code>string full_name = 2;</code>
     * @return string
     */
    public function getFullName()
    {
        return $this->full_name;
    }

    /**
     * full name
     *
     * Generated from protobuf field <code>string full_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFullName($var)
    {
        GPBUtil::checkString($var, True);
        $this->full_name = $var;

        return $this;
    }

    /**
     * email
     *
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * email
     *
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * password
     *
     * Generated from protobuf field <code>string password = 4;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * password
     *
     * Generated from protobuf field <code>string password = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * country
     *
     * Generated from protobuf field <code>string country = 5;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * country
     *
     * Generated from protobuf field <code>string country = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * birthday in format YYYY-MM-DD
     *
     * Generated from protobuf field <code>string birthday = 6;</code>
     * @return string
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * birthday in format YYYY-MM-DD
     *
     * Generated from protobuf field <code>string birthday = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBirthday($var)
    {
        GPBUtil::checkString($var, True);
        $this->birthday = $var;

        return $this;
    }

    /**
     * captcha challenge
     *
     * Generated from protobuf field <code>string captcha = 10;</code>
     * @return string
     */
    public function getCaptcha()
    {
        return $this->captcha;
    }

    /**
     * captcha challenge
     *
     * Generated from protobuf field <code>string captcha = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCaptcha($var)
    {
        GPBUtil::checkString($var, True);
        $this->captcha = $var;

        return $this;
    }

    /**
     * default locale for user
     *
     * Generated from protobuf field <code>string locale = 20;</code>
     * @return string
     */
    public function getLocale()
    {
        return $this->locale;
    }

    /**
     * default locale for user
     *
     * Generated from protobuf field <code>string locale = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setLocale($var)
    {
        GPBUtil::checkString($var, True);
        $this->locale = $var;

        return $this;
    }

}

