<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/cognito/cognito.proto

namespace Eolymp\Cognito;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Cognito\ListUsersInput\Filter instead.
     * @deprecated
     */
    class ListUsersInput_Filter {}
}
class_exists(ListUsersInput\Filter::class);
@trigger_error('Eolymp\Cognito\ListUsersInput_Filter is deprecated and will be removed in the next major release. Use Eolymp\Cognito\ListUsersInput\Filter instead', E_USER_DEPRECATED);

