<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/community/attribute.proto

namespace Eolymp\Community\Attribute;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Attribute value
 *
 * Generated from protobuf message <code>eolymp.community.Attribute.Value</code>
 */
class Value extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string attribute_key = 1;</code>
     */
    protected $attribute_key = '';
    /**
     * Generated from protobuf field <code>.eolymp.community.Attribute.Type attribute_type = 2;</code>
     */
    protected $attribute_type = 0;
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $attribute_key
     *     @type int $attribute_type
     *     @type string $string
     *     @type int $number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Community\Attribute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string attribute_key = 1;</code>
     * @return string
     */
    public function getAttributeKey()
    {
        return $this->attribute_key;
    }

    /**
     * Generated from protobuf field <code>string attribute_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAttributeKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->attribute_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.community.Attribute.Type attribute_type = 2;</code>
     * @return int
     */
    public function getAttributeType()
    {
        return $this->attribute_type;
    }

    /**
     * Generated from protobuf field <code>.eolymp.community.Attribute.Type attribute_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAttributeType($var)
    {
        GPBUtil::checkEnum($var, \Eolymp\Community\Attribute\Type::class);
        $this->attribute_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string = 10;</code>
     * @return string
     */
    public function getString()
    {
        return $this->readOneof(10);
    }

    public function hasString()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>string string = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setString($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 number = 11;</code>
     * @return int
     */
    public function getNumber()
    {
        return $this->readOneof(11);
    }

    public function hasNumber()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>int32 number = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Value::class, \Eolymp\Community\Attribute_Value::class);

