<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/localization/localization_service.proto

namespace Eolymp\Localization;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.localization.ApproveTermOutput</code>
 */
class ApproveTermOutput extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Localization\LocalizationService::initOnce();
        parent::__construct($data);
    }

}

