<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/content/post_service.proto

namespace Eolymp\Content\UpdatePostTranslationInput;

use UnexpectedValueException;

/**
 * Protobuf type <code>eolymp.content.UpdatePostTranslationInput.Patch</code>
 */
class Patch
{
    /**
     * Generated from protobuf enum <code>ALL = 0;</code>
     */
    const ALL = 0;
    /**
     * Generated from protobuf enum <code>CONTENT = 1;</code>
     */
    const CONTENT = 1;
    /**
     * Generated from protobuf enum <code>LABELS = 2;</code>
     */
    const LABELS = 2;
    /**
     * Generated from protobuf enum <code>LOCALE = 4;</code>
     */
    const LOCALE = 4;

    private static $valueToName = [
        self::ALL => 'ALL',
        self::CONTENT => 'CONTENT',
        self::LABELS => 'LABELS',
        self::LOCALE => 'LOCALE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

