<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/community/member_service.proto

namespace Eolymp\Community;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.community.DescribeUsageOutput</code>
 */
class DescribeUsageOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 active_members = 1;</code>
     */
    protected $active_members = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $active_members
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Community\MemberService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 active_members = 1;</code>
     * @return int
     */
    public function getActiveMembers()
    {
        return $this->active_members;
    }

    /**
     * Generated from protobuf field <code>uint32 active_members = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setActiveMembers($var)
    {
        GPBUtil::checkUint32($var);
        $this->active_members = $var;

        return $this;
    }

}

