<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/community/rating_point.proto

namespace Eolymp\Community;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.community.RatingPoint</code>
 */
class RatingPoint extends \Google\Protobuf\Internal\Message
{
    /**
     * unique rating point identifier
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * rating point time
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    protected $timestamp = null;
    /**
     * rating value
     *
     * Generated from protobuf field <code>uint32 value = 10;</code>
     */
    protected $value = 0;
    /**
     * contest_id which triggered rating change
     *
     * Generated from protobuf field <code>string contest_id = 20;</code>
     */
    protected $contest_id = '';
    /**
     * deprecated: keep empty
     *
     * Generated from protobuf field <code>string ref = 2;</code>
     */
    protected $ref = '';
    /**
     * deprecated: use contest_id instead
     *
     * Generated from protobuf field <code>string target_link = 22;</code>
     */
    protected $target_link = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           unique rating point identifier
     *     @type \Google\Protobuf\Timestamp $timestamp
     *           rating point time
     *     @type int $value
     *           rating value
     *     @type string $contest_id
     *           contest_id which triggered rating change
     *     @type string $ref
     *           deprecated: keep empty
     *     @type string $target_link
     *           deprecated: use contest_id instead
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Community\RatingPoint::initOnce();
        parent::__construct($data);
    }

    /**
     * unique rating point identifier
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * unique rating point identifier
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * rating point time
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * rating point time
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * rating value
     *
     * Generated from protobuf field <code>uint32 value = 10;</code>
     * @return int
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * rating value
     *
     * Generated from protobuf field <code>uint32 value = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkUint32($var);
        $this->value = $var;

        return $this;
    }

    /**
     * contest_id which triggered rating change
     *
     * Generated from protobuf field <code>string contest_id = 20;</code>
     * @return string
     */
    public function getContestId()
    {
        return $this->contest_id;
    }

    /**
     * contest_id which triggered rating change
     *
     * Generated from protobuf field <code>string contest_id = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setContestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->contest_id = $var;

        return $this;
    }

    /**
     * deprecated: keep empty
     *
     * Generated from protobuf field <code>string ref = 2;</code>
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * deprecated: keep empty
     *
     * Generated from protobuf field <code>string ref = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, True);
        $this->ref = $var;

        return $this;
    }

    /**
     * deprecated: use contest_id instead
     *
     * Generated from protobuf field <code>string target_link = 22;</code>
     * @return string
     */
    public function getTargetLink()
    {
        return $this->target_link;
    }

    /**
     * deprecated: use contest_id instead
     *
     * Generated from protobuf field <code>string target_link = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_link = $var;

        return $this;
    }

}

