<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/community/member_service.proto

namespace Eolymp\Community;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.community.StreamMemberReferencesOutput</code>
 */
class StreamMemberReferencesOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * up to ~1000 references per streamed message
     *
     * Generated from protobuf field <code>repeated .eolymp.community.Member.Reference items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Eolymp\Community\Member\Reference>|\Google\Protobuf\Internal\RepeatedField $items
     *           up to ~1000 references per streamed message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Community\MemberService::initOnce();
        parent::__construct($data);
    }

    /**
     * up to ~1000 references per streamed message
     *
     * Generated from protobuf field <code>repeated .eolymp.community.Member.Reference items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * up to ~1000 references per streamed message
     *
     * Generated from protobuf field <code>repeated .eolymp.community.Member.Reference items = 1;</code>
     * @param array<\Eolymp\Community\Member\Reference>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eolymp\Community\Member\Reference::class);
        $this->items = $arr;

        return $this;
    }

}

