<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/community/account_service.proto

namespace Eolymp\Community;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Community\UpdateAccountInput\Patch instead.
     * @deprecated
     */
    class UpdateAccountInput_Patch {}
}
class_exists(UpdateAccountInput\Patch::class);
@trigger_error('Eolymp\Community\UpdateAccountInput_Patch is deprecated and will be removed in the next major release. Use Eolymp\Community\UpdateAccountInput\Patch instead', E_USER_DEPRECATED);

