<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/atlas/test.proto

namespace GPBMetadata\Eolymp\Atlas;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aef010a17656f6c796d702f61746c61732f746573742e70726f746f120c656f6c796d702e61746c61732288010a0454657374120a0a02696418012001280912120a0a746573747365745f6964180220012809120d0a05696e646578180320012805120f0a076578616d706c65180420012808120d0a0573636f726518052001280212170a0f696e7075745f6f626a6563745f6964180a2001280912180a10616e737765725f6f626a6563745f696418142001280942335a316769746875622e636f6d2f656f6c796d702f636f6e7472616374732f676f2f656f6c796d702f61746c61733b61746c6173620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

