<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/judge/tasks.proto

namespace Eolymp\Judge\RetestProblemTask;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Checkpoint records how far the retest got, so a restarted task resumes instead of re-submitting
 * everything from the beginning.
 *
 * Generated from protobuf message <code>eolymp.judge.RetestProblemTask.Checkpoint</code>
 */
class Checkpoint extends \Google\Protobuf\Internal\Message
{
    /**
     * Submissions are retested in submission order; submissions submitted before this moment have
     * been retested already.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp submitted_before = 1;</code>
     */
    protected $submitted_before = null;
    /**
     * Number of submissions retested so far.
     *
     * Generated from protobuf field <code>uint32 retested = 2;</code>
     */
    protected $retested = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $submitted_before
     *           Submissions are retested in submission order; submissions submitted before this moment have
     *           been retested already.
     *     @type int $retested
     *           Number of submissions retested so far.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Judge\Tasks::initOnce();
        parent::__construct($data);
    }

    /**
     * Submissions are retested in submission order; submissions submitted before this moment have
     * been retested already.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp submitted_before = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getSubmittedBefore()
    {
        return $this->submitted_before;
    }

    public function hasSubmittedBefore()
    {
        return isset($this->submitted_before);
    }

    public function clearSubmittedBefore()
    {
        unset($this->submitted_before);
    }

    /**
     * Submissions are retested in submission order; submissions submitted before this moment have
     * been retested already.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp submitted_before = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setSubmittedBefore($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->submitted_before = $var;

        return $this;
    }

    /**
     * Number of submissions retested so far.
     *
     * Generated from protobuf field <code>uint32 retested = 2;</code>
     * @return int
     */
    public function getRetested()
    {
        return $this->retested;
    }

    /**
     * Number of submissions retested so far.
     *
     * Generated from protobuf field <code>uint32 retested = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRetested($var)
    {
        GPBUtil::checkUint32($var);
        $this->retested = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Checkpoint::class, \Eolymp\Judge\RetestProblemTask_Checkpoint::class);

