<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/wellknown/link.proto

namespace GPBMetadata\Eolymp\Wellknown;

class Link
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e010a1b656f6c796d702f77656c6c6b6e6f776e2f6c696e6b2e70726f746f1210656f6c796d702e77656c6c6b6e6f776e222e0a044c696e6b120b0a0372656c180120012809120b0a03726566180220012809120c0a047479706518032001280942355a336769746875622e636f6d2f656f6c796d702f676f2d73646b2f656f6c796d702f77656c6c6b6e6f776e3b77656c6c6b6e6f776e620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

