<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/community/group.proto

namespace GPBMetadata\Eolymp\Community;

class Group
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD3\x02\x0A\x1Ceolymp/community/group.proto\x12\x10eolymp.community\"\xE1\x01\x0A\x05Group\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x0B\x0A\x03key\x18\x04 \x01(\x09\x12\x0C\x0A\x04name\x18\x02 \x01(\x09\x12\x13\x0A\x0Bdescription\x18\x03 \x01(\x09\x12\x0D\x0A\x05index\x18\x05 \x01(\x0D\x12\x0C\x0A\x04icon\x18\x0A \x01(\x09\x12\x0D\x0A\x05badge\x18\x0B \x01(\x09\x12\x0D\x0A\x05color\x18\x0C \x01(\x09\x1Aa\x0A\x05Patch\"X\x0A\x05Field\x12\x0B\x0A\x07UNKNOWN\x10\x00\x12\x08\x0A\x04NAME\x10\x01\x12\x0F\x0A\x0BDESCRIPTION\x10\x02\x12\x07\x0A\x03KEY\x10\x03\x12\x08\x0A\x04ICON\x10\x04\x12\x09\x0A\x05BADGE\x10\x05\x12\x09\x0A\x05COLOR\x10\x06B5Z3github.com/eolymp/go-sdk/eolymp/community;communityb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

