<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/resolver/resolver.proto

namespace Eolymp\Resolver;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Resolver\Record\Target instead.
     * @deprecated
     */
    class Record_Target {}
}
class_exists(Record\Target::class);
@trigger_error('Eolymp\Resolver\Record_Target is deprecated and will be removed in the next major release. Use Eolymp\Resolver\Record\Target instead', E_USER_DEPRECATED);

