<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/judge/problem_service.proto

namespace Eolymp\Judge\UpdateProblemInput;

use UnexpectedValueException;

/**
 * Protobuf type <code>eolymp.judge.UpdateProblemInput.Patch</code>
 */
class Patch
{
    /**
     * Generated from protobuf enum <code>ALL = 0;</code>
     */
    const ALL = 0;
    /**
     * Generated from protobuf enum <code>INDEX = 1;</code>
     */
    const INDEX = 1;
    /**
     * Generated from protobuf enum <code>SUBMIT_LIMIT = 2;</code>
     */
    const SUBMIT_LIMIT = 2;
    /**
     * Generated from protobuf enum <code>SCORE_BY_BEST_TESTSET = 3;</code>
     */
    const SCORE_BY_BEST_TESTSET = 3;

    private static $valueToName = [
        self::ALL => 'ALL',
        self::INDEX => 'INDEX',
        self::SUBMIT_LIMIT => 'SUBMIT_LIMIT',
        self::SCORE_BY_BEST_TESTSET => 'SCORE_BY_BEST_TESTSET',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

