<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/atlas/change.proto

namespace Eolymp\Atlas;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Atlas\Change\UpdateTemplate instead.
     * @deprecated
     */
    class Change_UpdateTemplate {}
}
class_exists(Change\UpdateTemplate::class);
@trigger_error('Eolymp\Atlas\Change_UpdateTemplate is deprecated and will be removed in the next major release. Use Eolymp\Atlas\Change\UpdateTemplate instead', E_USER_DEPRECATED);

