<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/atlas/configuration.proto

namespace Eolymp\Atlas;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.atlas.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * max submissions per IP per hour; 0 = unlimited
     *
     * Generated from protobuf field <code>uint32 hourly_ip_submission_limit = 1;</code>
     */
    protected $hourly_ip_submission_limit = 0;
    /**
     * max submissions per IP per day; 0 = unlimited
     *
     * Generated from protobuf field <code>uint32 daily_ip_submission_limit = 2;</code>
     */
    protected $daily_ip_submission_limit = 0;
    /**
     * Offer traced runs in the editor. A traced run is built and executed differently and
     * costs orders of magnitude more CPU, so it is opt-in per space.
     *
     * Generated from protobuf field <code>bool tracing_enabled = 3;</code>
     */
    protected $tracing_enabled = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $hourly_ip_submission_limit
     *           max submissions per IP per hour; 0 = unlimited
     *     @type int $daily_ip_submission_limit
     *           max submissions per IP per day; 0 = unlimited
     *     @type bool $tracing_enabled
     *           Offer traced runs in the editor. A traced run is built and executed differently and
     *           costs orders of magnitude more CPU, so it is opt-in per space.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Atlas\Configuration::initOnce();
        parent::__construct($data);
    }

    /**
     * max submissions per IP per hour; 0 = unlimited
     *
     * Generated from protobuf field <code>uint32 hourly_ip_submission_limit = 1;</code>
     * @return int
     */
    public function getHourlyIpSubmissionLimit()
    {
        return $this->hourly_ip_submission_limit;
    }

    /**
     * max submissions per IP per hour; 0 = unlimited
     *
     * Generated from protobuf field <code>uint32 hourly_ip_submission_limit = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setHourlyIpSubmissionLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->hourly_ip_submission_limit = $var;

        return $this;
    }

    /**
     * max submissions per IP per day; 0 = unlimited
     *
     * Generated from protobuf field <code>uint32 daily_ip_submission_limit = 2;</code>
     * @return int
     */
    public function getDailyIpSubmissionLimit()
    {
        return $this->daily_ip_submission_limit;
    }

    /**
     * max submissions per IP per day; 0 = unlimited
     *
     * Generated from protobuf field <code>uint32 daily_ip_submission_limit = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDailyIpSubmissionLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->daily_ip_submission_limit = $var;

        return $this;
    }

    /**
     * Offer traced runs in the editor. A traced run is built and executed differently and
     * costs orders of magnitude more CPU, so it is opt-in per space.
     *
     * Generated from protobuf field <code>bool tracing_enabled = 3;</code>
     * @return bool
     */
    public function getTracingEnabled()
    {
        return $this->tracing_enabled;
    }

    /**
     * Offer traced runs in the editor. A traced run is built and executed differently and
     * costs orders of magnitude more CPU, so it is opt-in per space.
     *
     * Generated from protobuf field <code>bool tracing_enabled = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setTracingEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->tracing_enabled = $var;

        return $this;
    }

}

