<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/atlas/atlas.proto

namespace Eolymp\Atlas;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.atlas.DescribeTaxonomyOutput</code>
 */
class DescribeTaxonomyOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string tags = 5;</code>
     */
    private $tags;
    /**
     * Generated from protobuf field <code>string competition = 10;</code>
     */
    protected $competition = '';
    /**
     * Generated from protobuf field <code>uint32 year = 11;</code>
     */
    protected $year = 0;
    /**
     * Generated from protobuf field <code>uint32 stage = 12;</code>
     */
    protected $stage = 0;
    /**
     * Generated from protobuf field <code>uint32 round = 13;</code>
     */
    protected $round = 0;
    /**
     * Generated from protobuf field <code>string country = 20;</code>
     */
    protected $country = '';
    /**
     * Generated from protobuf field <code>string region = 21;</code>
     */
    protected $region = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     *     @type string $competition
     *     @type int $year
     *     @type int $stage
     *     @type int $round
     *     @type string $country
     *     @type string $region
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Atlas\Atlas::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string competition = 10;</code>
     * @return string
     */
    public function getCompetition()
    {
        return $this->competition;
    }

    /**
     * Generated from protobuf field <code>string competition = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCompetition($var)
    {
        GPBUtil::checkString($var, True);
        $this->competition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 year = 11;</code>
     * @return int
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>uint32 year = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkUint32($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 stage = 12;</code>
     * @return int
     */
    public function getStage()
    {
        return $this->stage;
    }

    /**
     * Generated from protobuf field <code>uint32 stage = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setStage($var)
    {
        GPBUtil::checkUint32($var);
        $this->stage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 round = 13;</code>
     * @return int
     */
    public function getRound()
    {
        return $this->round;
    }

    /**
     * Generated from protobuf field <code>uint32 round = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setRound($var)
    {
        GPBUtil::checkUint32($var);
        $this->round = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country = 20;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>string country = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string region = 21;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>string region = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->region = $var;

        return $this;
    }

}

