<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/atlas/editorial.proto

namespace Eolymp\Atlas;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Atlas\Editorial\Extra instead.
     * @deprecated
     */
    class Editorial_Extra {}
}
class_exists(Editorial\Extra::class);
@trigger_error('Eolymp\Atlas\Editorial_Extra is deprecated and will be removed in the next major release. Use Eolymp\Atlas\Editorial\Extra instead', E_USER_DEPRECATED);

