<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/atlas/solution.proto

namespace Eolymp\Atlas;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.atlas.Solution</code>
 */
class Solution extends \Google\Protobuf\Internal\Message
{
    /**
     * unique identifier
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * solution name
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * runtime and source are secret
     *
     * Generated from protobuf field <code>bool secret = 4;</code>
     */
    protected $secret = false;
    /**
     * programming language
     *
     * Generated from protobuf field <code>string runtime = 10;</code>
     */
    protected $runtime = '';
    /**
     * source code
     *
     * Generated from protobuf field <code>string source = 11;</code>
     */
    protected $source = '';
    /**
     * expected outcome; the fallback for any testset not named in assertions, and the only thing checked when assertions is empty
     *
     * Generated from protobuf field <code>.eolymp.atlas.Solution.Type type = 20;</code>
     */
    protected $type = 0;
    /**
     * per-testset overrides. Changes only how CheckSolutions grades the result: the solution still runs as one
     * submission either way. Empty means the solution is graded on the submission as a whole, exactly as
     * before this field existed. Invalid on a solution whose own type is DONT_RUN or FAILURE.
     *
     * Generated from protobuf field <code>repeated .eolymp.atlas.Solution.Assertion assertions = 21;</code>
     */
    private $assertions;
    /**
     * Generated from protobuf field <code>.eolymp.atlas.Solution.Status status = 30;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string submission_id = 31;</code>
     */
    protected $submission_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           unique identifier
     *     @type string $name
     *           solution name
     *     @type bool $secret
     *           runtime and source are secret
     *     @type string $runtime
     *           programming language
     *     @type string $source
     *           source code
     *     @type int $type
     *           expected outcome; the fallback for any testset not named in assertions, and the only thing checked when assertions is empty
     *     @type array<\Eolymp\Atlas\Solution\Assertion>|\Google\Protobuf\Internal\RepeatedField $assertions
     *           per-testset overrides. Changes only how CheckSolutions grades the result: the solution still runs as one
     *           submission either way. Empty means the solution is graded on the submission as a whole, exactly as
     *           before this field existed. Invalid on a solution whose own type is DONT_RUN or FAILURE.
     *     @type int $status
     *     @type string $submission_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Atlas\Solution::initOnce();
        parent::__construct($data);
    }

    /**
     * unique identifier
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * unique identifier
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * solution name
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * solution name
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * runtime and source are secret
     *
     * Generated from protobuf field <code>bool secret = 4;</code>
     * @return bool
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * runtime and source are secret
     *
     * Generated from protobuf field <code>bool secret = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkBool($var);
        $this->secret = $var;

        return $this;
    }

    /**
     * programming language
     *
     * Generated from protobuf field <code>string runtime = 10;</code>
     * @return string
     */
    public function getRuntime()
    {
        return $this->runtime;
    }

    /**
     * programming language
     *
     * Generated from protobuf field <code>string runtime = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setRuntime($var)
    {
        GPBUtil::checkString($var, True);
        $this->runtime = $var;

        return $this;
    }

    /**
     * source code
     *
     * Generated from protobuf field <code>string source = 11;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * source code
     *
     * Generated from protobuf field <code>string source = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * expected outcome; the fallback for any testset not named in assertions, and the only thing checked when assertions is empty
     *
     * Generated from protobuf field <code>.eolymp.atlas.Solution.Type type = 20;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * expected outcome; the fallback for any testset not named in assertions, and the only thing checked when assertions is empty
     *
     * Generated from protobuf field <code>.eolymp.atlas.Solution.Type type = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Eolymp\Atlas\Solution\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * per-testset overrides. Changes only how CheckSolutions grades the result: the solution still runs as one
     * submission either way. Empty means the solution is graded on the submission as a whole, exactly as
     * before this field existed. Invalid on a solution whose own type is DONT_RUN or FAILURE.
     *
     * Generated from protobuf field <code>repeated .eolymp.atlas.Solution.Assertion assertions = 21;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAssertions()
    {
        return $this->assertions;
    }

    /**
     * per-testset overrides. Changes only how CheckSolutions grades the result: the solution still runs as one
     * submission either way. Empty means the solution is graded on the submission as a whole, exactly as
     * before this field existed. Invalid on a solution whose own type is DONT_RUN or FAILURE.
     *
     * Generated from protobuf field <code>repeated .eolymp.atlas.Solution.Assertion assertions = 21;</code>
     * @param array<\Eolymp\Atlas\Solution\Assertion>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAssertions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eolymp\Atlas\Solution\Assertion::class);
        $this->assertions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Solution.Status status = 30;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Solution.Status status = 30;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Eolymp\Atlas\Solution\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string submission_id = 31;</code>
     * @return string
     */
    public function getSubmissionId()
    {
        return $this->submission_id;
    }

    /**
     * Generated from protobuf field <code>string submission_id = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setSubmissionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->submission_id = $var;

        return $this;
    }

}

