<?php
# Generated by the protocol buffer compiler. DO NOT EDIT!
# See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-php-esdk for more details.

namespace Eolymp\Atlas;

    /**
     * StatementService manages problem statements.
     *
     * A statement is the problem text for one locale, and a problem normally has one statement per language so a
     * participant can read it in their own. Content is Markdown or LaTeX, split into sections by markers placed on
     * their own line (`\InputFile`, `\Interaction`, `\OutputFile`, `\Examples`, `\Note`, `\Scoring`), and the text
     * before the first marker is the introduction. Never write the `\Examples` section by hand: it is generated
     * from the tests marked as examples. Content is returned only when requested, either in its raw form for
     * editing or as a parsed tree for display. A call takes its problem from `problem_id`, or from the problem url when the field is empty.
     */
class StatementServiceClient {

    /** @var string base URL */
    private $url;

    /** @var callable RPC client */
    private $invoker;

    /**
     * @param string   $url     defines base URL for service
     * @param callable $invoker provides transport implementation for calls
     */
    public function __construct($url, $invoker)
    {
        $this->url = $url;
        $this->invoker = $invoker;
    }

    /**
     * CreateStatement adds the statement for one locale and returns its id. Publishing the same problem in
     * another language means creating another statement, not editing this one.
     *
     * @param CreateStatementInput $input message
     * @param array $context request parameters
     *
     * @return CreateStatementOutput output message
     */
    public function CreateStatement(CreateStatementInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/statements";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");

        $context['name'] = "eolymp.atlas.StatementService/CreateStatement";
        $context['path'] = $path;

        return call_user_func($this->invoker, "PUT", $this->url.$path, $input, CreateStatementOutput::class, $context);
    }

    /**
     * UpdateStatement writes new values into an existing statement. Fields outside the patch mask keep the
     * values they already have, so a title fix does not require resending the content.
     *
     * @param UpdateStatementInput $input message
     * @param array $context request parameters
     *
     * @return UpdateStatementOutput output message
     */
    public function UpdateStatement(UpdateStatementInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/statements/".rawurlencode($input->getStatementId());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");
        $input->setStatementId("");

        $context['name'] = "eolymp.atlas.StatementService/UpdateStatement";
        $context['path'] = $path;

        return call_user_func($this->invoker, "PUT", $this->url.$path, $input, UpdateStatementOutput::class, $context);
    }

    /**
     * DeleteStatement permanently removes a single locale of the problem text. The problem itself and its
     * statements in other locales are left untouched.
     *
     * @param DeleteStatementInput $input message
     * @param array $context request parameters
     *
     * @return DeleteStatementOutput output message
     */
    public function DeleteStatement(DeleteStatementInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/statements/".rawurlencode($input->getStatementId());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");
        $input->setStatementId("");

        $context['name'] = "eolymp.atlas.StatementService/DeleteStatement";
        $context['path'] = $path;

        return call_user_func($this->invoker, "DELETE", $this->url.$path, $input, DeleteStatementOutput::class, $context);
    }

    /**
     * DescribeStatement returns a single statement by id, for callers that already know which locale they want;
     * its content is left out unless requested, in raw or rendered form.
     *
     * @param DescribeStatementInput $input message
     * @param array $context request parameters
     *
     * @return DescribeStatementOutput output message
     */
    public function DescribeStatement(DescribeStatementInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/statements/".rawurlencode($input->getStatementId());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");
        $input->setStatementId("");

        $context['name'] = "eolymp.atlas.StatementService/DescribeStatement";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, DescribeStatementOutput::class, $context);
    }

    /**
     * LookupStatement finds a statement by locale instead of by id, and the server falls back to another locale
     * when the requested one does not exist — this is how a client renders a problem for a particular reader.
     *
     * @param LookupStatementInput $input message
     * @param array $context request parameters
     *
     * @return LookupStatementOutput output message
     */
    public function LookupStatement(LookupStatementInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/translate";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");

        $context['name'] = "eolymp.atlas.StatementService/LookupStatement";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, LookupStatementOutput::class, $context);
    }

    /**
     * PreviewStatement renders a draft statement sent in the request, before it has been saved. Nothing is read
     * from or written to stored data, which makes it suitable for a live preview pane next to the editor.
     *
     * @param PreviewStatementInput $input message
     * @param array $context request parameters
     *
     * @return PreviewStatementOutput output message
     */
    public function PreviewStatement(PreviewStatementInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/renders";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");

        $context['name'] = "eolymp.atlas.StatementService/PreviewStatement";
        $context['path'] = $path;

        return call_user_func($this->invoker, "POST", $this->url.$path, $input, PreviewStatementOutput::class, $context);
    }

    /**
     * ListStatements returns the problem's statements, one per locale, which is how to discover the languages a
     * problem is available in. Their content is left out unless requested.
     *
     * @param ListStatementsInput $input message
     * @param array $context request parameters
     *
     * @return ListStatementsOutput output message
     */
    public function ListStatements(ListStatementsInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/statements";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");

        $context['name'] = "eolymp.atlas.StatementService/ListStatements";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, ListStatementsOutput::class, $context);
    }

    /**
     * TranslateStatements starts automatic translation of a statement into other locales and returns a job id;
     * the translation runs asynchronously, so the target statements appear some time after the call returns and
     * are found by listing them again. Statements written by hand are not overwritten unless the request asks
     * for it, and the produced statements are marked as automatic.
     *
     * @param TranslateStatementsInput $input message
     * @param array $context request parameters
     *
     * @return TranslateStatementsOutput output message
     */
    public function TranslateStatements(TranslateStatementsInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/statements:translate";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");

        $context['name'] = "eolymp.atlas.StatementService/TranslateStatements";
        $context['path'] = $path;

        return call_user_func($this->invoker, "POST", $this->url.$path, $input, TranslateStatementsOutput::class, $context);
    }

    /**
     * ExportStatement renders a saved statement into a downloadable document, offered in the console as
     * "Export to PDF". The response carries a link to fetch the document, not the document itself.
     *
     * @param ExportStatementInput $input message
     * @param array $context request parameters
     *
     * @return ExportStatementOutput output message
     */
    public function ExportStatement(ExportStatementInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/statements/".rawurlencode($input->getStatementId())."/export";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");
        $input->setStatementId("");

        $context['name'] = "eolymp.atlas.StatementService/ExportStatement";
        $context['path'] = $path;

        return call_user_func($this->invoker, "POST", $this->url.$path, $input, ExportStatementOutput::class, $context);
    }

    /**
     * ListStatementVersions returns earlier revisions of one statement, so a client can show a history or
     * compare two revisions. Each revision comes back as a whole statement rather than as version metadata, with
     * its content left out unless requested.
     *
     * @param ListStatementVersionsInput $input message
     * @param array $context request parameters
     *
     * @return ListStatementVersionsOutput output message
     */
    public function ListStatementVersions(ListStatementVersionsInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/statements/".rawurlencode($input->getStatementId())."/versions";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");
        $input->setStatementId("");

        $context['name'] = "eolymp.atlas.StatementService/ListStatementVersions";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, ListStatementVersionsOutput::class, $context);
    }

}
