<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/atlas/submission.proto

namespace Eolymp\Atlas;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Atlas\Submission\VerifierExecutionData instead.
     * @deprecated
     */
    class Submission_VerifierExecutionData {}
}
class_exists(Submission\VerifierExecutionData::class);
@trigger_error('Eolymp\Atlas\Submission_VerifierExecutionData is deprecated and will be removed in the next major release. Use Eolymp\Atlas\Submission\VerifierExecutionData instead', E_USER_DEPRECATED);

