<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/atlas/submission.proto

namespace Eolymp\Atlas;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Atlas\Submission\Group\ScoringMode instead.
     * @deprecated
     */
    class Submission_Group_ScoringMode {}
}
class_exists(Submission\Group\ScoringMode::class);
@trigger_error('Eolymp\Atlas\Submission_Group_ScoringMode is deprecated and will be removed in the next major release. Use Eolymp\Atlas\Submission\Group\ScoringMode instead', E_USER_DEPRECATED);

