<?php
# Generated by the protocol buffer compiler. DO NOT EDIT!
# See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-php-esdk for more details.

namespace Eolymp\Atlas;

    /**
     * internal
     *
     * SuggestionService collects community-proposed changes to a problem and drives their review.
     *
     * A suggestion is an edit proposed by a user of the public archive rather than by the problem's own owners: a
     * corrected statement for one locale, a new or improved editorial, or a different classification. It records
     * who wrote it and the problem version it was written against, and moves from pending through review to
     * approved or rejected. A moderator settles it with ReviewSuggestion, and the author can revise a rejected one
     * and send it back with ResubmitSuggestion. In practice this is the archive-curation API: the console only
     * exposes the review side of it, for the Basecamp space.
     */
class SuggestionServiceClient {

    /** @var string base URL */
    private $url;

    /** @var callable RPC client */
    private $invoker;

    /**
     * @param string   $url     defines base URL for service
     * @param callable $invoker provides transport implementation for calls
     */
    public function __construct($url, $invoker)
    {
        $this->url = $url;
        $this->invoker = $invoker;
    }

    /**
     * CreateSuggestion submits a proposed change to the problem and returns its id. A suggestion carries exactly
     * one kind of change, so proposing two kinds means two suggestions. It changes nothing about the problem on
     * its own, it waits for review.
     *
     * @param CreateSuggestionInput $input message
     * @param array $context request parameters
     *
     * @return CreateSuggestionOutput output message
     */
    public function CreateSuggestion(CreateSuggestionInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/suggestions";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");

        $context['name'] = "eolymp.atlas.SuggestionService/CreateSuggestion";
        $context['path'] = $path;

        return call_user_func($this->invoker, "POST", $this->url.$path, $input, CreateSuggestionOutput::class, $context);
    }

    /**
     * UpdateSuggestion replaces the change a suggestion carries, which is how its author revises it. There is no
     * patch here, the suggestion in the request is taken as a whole, so resend the complete change.
     *
     * @param UpdateSuggestionInput $input message
     * @param array $context request parameters
     *
     * @return UpdateSuggestionOutput output message
     */
    public function UpdateSuggestion(UpdateSuggestionInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/suggestions/".rawurlencode($input->getSuggestionId());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");
        $input->setSuggestionId("");

        $context['name'] = "eolymp.atlas.SuggestionService/UpdateSuggestion";
        $context['path'] = $path;

        return call_user_func($this->invoker, "POST", $this->url.$path, $input, UpdateSuggestionOutput::class, $context);
    }

    /**
     * ReviewSuggestion is how a moderator rules on a suggestion. Approving and rejecting are the same call with a
     * different review outcome rather than two separate rpcs, and a suggestion can also be flagged as being
     * looked at. The contribution scores how much the suggestion was worth, from 0 for insignificant to 5 for
     * major.
     *
     * @param ReviewSuggestionInput $input message
     * @param array $context request parameters
     *
     * @return ReviewSuggestionOutput output message
     */
    public function ReviewSuggestion(ReviewSuggestionInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/suggestions/".rawurlencode($input->getSuggestionId())."/review";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");
        $input->setSuggestionId("");

        $context['name'] = "eolymp.atlas.SuggestionService/ReviewSuggestion";
        $context['path'] = $path;

        return call_user_func($this->invoker, "POST", $this->url.$path, $input, ReviewSuggestionOutput::class, $context);
    }

    /**
     * ResubmitSuggestion puts a suggestion back in front of the moderators, which is how a rejected one re-enters
     * the queue. It carries no content, so write the revised change with UpdateSuggestion first.
     *
     * @param ResubmitSuggestionInput $input message
     * @param array $context request parameters
     *
     * @return ResubmitSuggestionOutput output message
     */
    public function ResubmitSuggestion(ResubmitSuggestionInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/suggestions/".rawurlencode($input->getSuggestionId())."/resubmit";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");
        $input->setSuggestionId("");

        $context['name'] = "eolymp.atlas.SuggestionService/ResubmitSuggestion";
        $context['path'] = $path;

        return call_user_func($this->invoker, "POST", $this->url.$path, $input, ResubmitSuggestionOutput::class, $context);
    }

    /**
     * DeleteSuggestion removes a suggestion outright, leaving no record that it was ever made. Prefer rejecting it
     * when the decision is worth keeping: a rejected suggestion can still be revised and resubmitted, a deleted
     * one cannot.
     *
     * @param DeleteSuggestionInput $input message
     * @param array $context request parameters
     *
     * @return DeleteSuggestionOutput output message
     */
    public function DeleteSuggestion(DeleteSuggestionInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/suggestions/".rawurlencode($input->getSuggestionId());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");
        $input->setSuggestionId("");

        $context['name'] = "eolymp.atlas.SuggestionService/DeleteSuggestion";
        $context['path'] = $path;

        return call_user_func($this->invoker, "DELETE", $this->url.$path, $input, DeleteSuggestionOutput::class, $context);
    }

    /**
     * ListSuggestions returns the suggestions made for one problem; filtering on the pending ones gives the review
     * queue. Items are complete, including the change proposed, so triage rarely needs DescribeSuggestion.
     *
     * @param ListSuggestionsInput $input message
     * @param array $context request parameters
     *
     * @return ListSuggestionsOutput output message
     */
    public function ListSuggestions(ListSuggestionsInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/suggestions";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");

        $context['name'] = "eolymp.atlas.SuggestionService/ListSuggestions";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, ListSuggestionsOutput::class, $context);
    }

    /**
     * DescribeSuggestion returns one suggestion together with the change it proposes. Compare the problem version
     * it was written against with the problem's current version to see whether the problem has moved on since.
     *
     * @param DescribeSuggestionInput $input message
     * @param array $context request parameters
     *
     * @return DescribeSuggestionOutput output message
     */
    public function DescribeSuggestion(DescribeSuggestionInput $input, array $context = [])
    {
        $path = "/problems/".rawurlencode($input->getProblemId())."/suggestions/".rawurlencode($input->getSuggestionId());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setProblemId("");
        $input->setSuggestionId("");

        $context['name'] = "eolymp.atlas.SuggestionService/DescribeSuggestion";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, DescribeSuggestionOutput::class, $context);
    }

}
