<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/atlas/suggestion.proto

namespace Eolymp\Atlas;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Atlas\Suggestion\EditorialChange instead.
     * @deprecated
     */
    class Suggestion_EditorialChange {}
}
class_exists(Suggestion\EditorialChange::class);
@trigger_error('Eolymp\Atlas\Suggestion_EditorialChange is deprecated and will be removed in the next major release. Use Eolymp\Atlas\Suggestion\EditorialChange instead', E_USER_DEPRECATED);

