<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/atlas/suggestion.proto

namespace Eolymp\Atlas;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>eolymp.atlas.Suggestion</code>
 */
class Suggestion extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.eolymp.atlas.Suggestion.Status status = 2;</code>
     */
    protected $status = 0;
    /**
     * problem version this suggestion applies to
     *
     * Generated from protobuf field <code>uint32 version = 8;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>string member_id = 5;</code>
     */
    protected $member_id = '';
    /**
     * contribution score 0 - not significant or between 1 (minor) - 5 (major)
     *
     * Generated from protobuf field <code>uint32 contribution = 7;</code>
     */
    protected $contribution = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 10;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 11;</code>
     */
    protected $updated_at = null;
    protected $change;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type int $status
     *     @type int $version
     *           problem version this suggestion applies to
     *     @type string $member_id
     *     @type int $contribution
     *           contribution score 0 - not significant or between 1 (minor) - 5 (major)
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     *     @type \Eolymp\Atlas\Suggestion\Classification $classification
     *     @type \Eolymp\Atlas\Suggestion\StatementChange $statement_change
     *     @type \Eolymp\Atlas\Suggestion\EditorialChange $editorial_change
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Atlas\Suggestion::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Suggestion.Status status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Suggestion.Status status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Eolymp\Atlas\Suggestion\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * problem version this suggestion applies to
     *
     * Generated from protobuf field <code>uint32 version = 8;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * problem version this suggestion applies to
     *
     * Generated from protobuf field <code>uint32 version = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_id = 5;</code>
     * @return string
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Generated from protobuf field <code>string member_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_id = $var;

        return $this;
    }

    /**
     * contribution score 0 - not significant or between 1 (minor) - 5 (major)
     *
     * Generated from protobuf field <code>uint32 contribution = 7;</code>
     * @return int
     */
    public function getContribution()
    {
        return $this->contribution;
    }

    /**
     * contribution score 0 - not significant or between 1 (minor) - 5 (major)
     *
     * Generated from protobuf field <code>uint32 contribution = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setContribution($var)
    {
        GPBUtil::checkUint32($var);
        $this->contribution = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 10;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 10;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 11;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 11;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Suggestion.Classification classification = 100;</code>
     * @return \Eolymp\Atlas\Suggestion\Classification|null
     */
    public function getClassification()
    {
        return $this->readOneof(100);
    }

    public function hasClassification()
    {
        return $this->hasOneof(100);
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Suggestion.Classification classification = 100;</code>
     * @param \Eolymp\Atlas\Suggestion\Classification $var
     * @return $this
     */
    public function setClassification($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Atlas\Suggestion\Classification::class);
        $this->writeOneof(100, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Suggestion.StatementChange statement_change = 101;</code>
     * @return \Eolymp\Atlas\Suggestion\StatementChange|null
     */
    public function getStatementChange()
    {
        return $this->readOneof(101);
    }

    public function hasStatementChange()
    {
        return $this->hasOneof(101);
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Suggestion.StatementChange statement_change = 101;</code>
     * @param \Eolymp\Atlas\Suggestion\StatementChange $var
     * @return $this
     */
    public function setStatementChange($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Atlas\Suggestion\StatementChange::class);
        $this->writeOneof(101, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Suggestion.EditorialChange editorial_change = 102;</code>
     * @return \Eolymp\Atlas\Suggestion\EditorialChange|null
     */
    public function getEditorialChange()
    {
        return $this->readOneof(102);
    }

    public function hasEditorialChange()
    {
        return $this->hasOneof(102);
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Suggestion.EditorialChange editorial_change = 102;</code>
     * @param \Eolymp\Atlas\Suggestion\EditorialChange $var
     * @return $this
     */
    public function setEditorialChange($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Atlas\Suggestion\EditorialChange::class);
        $this->writeOneof(102, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getChange()
    {
        return $this->whichOneof("change");
    }

}

