<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/atlas/issue_service.proto

namespace Eolymp\Atlas;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.atlas.UpdateIssueInput</code>
 */
class UpdateIssueInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string issue_id = 2;</code>
     */
    protected $issue_id = '';
    /**
     * Generated from protobuf field <code>.eolymp.atlas.Issue.Patch issue = 4;</code>
     */
    protected $issue = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $issue_id
     *     @type \Eolymp\Atlas\Issue\Patch $issue
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Atlas\IssueService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string issue_id = 2;</code>
     * @return string
     */
    public function getIssueId()
    {
        return $this->issue_id;
    }

    /**
     * Generated from protobuf field <code>string issue_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIssueId($var)
    {
        GPBUtil::checkString($var, True);
        $this->issue_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Issue.Patch issue = 4;</code>
     * @return \Eolymp\Atlas\Issue\Patch|null
     */
    public function getIssue()
    {
        return $this->issue;
    }

    public function hasIssue()
    {
        return isset($this->issue);
    }

    public function clearIssue()
    {
        unset($this->issue);
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Issue.Patch issue = 4;</code>
     * @param \Eolymp\Atlas\Issue\Patch $var
     * @return $this
     */
    public function setIssue($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Atlas\Issue\Patch::class);
        $this->issue = $var;

        return $this;
    }

}

