<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/content/post.proto

namespace Eolymp\Content\Post;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.content.Post.Patch</code>
 */
class Patch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string type_id = 6;</code>
     */
    protected $type_id = null;
    /**
     * Generated from protobuf field <code>optional bool featured = 9;</code>
     */
    protected $featured = null;
    /**
     * Generated from protobuf field <code>optional bool pinned = 13;</code>
     */
    protected $pinned = null;
    /**
     * Generated from protobuf field <code>optional bool automatic = 14;</code>
     */
    protected $automatic = null;
    /**
     * Generated from protobuf field <code>.eolymp.ecm.Content content = 101;</code>
     */
    protected $content = null;
    /**
     * Generated from protobuf field <code>repeated string labels = 120;</code>
     */
    private $labels;
    /**
     * clears the labels, which an empty list cannot express
     *
     * Generated from protobuf field <code>optional bool unlabel = 121;</code>
     */
    protected $unlabel = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type_id
     *     @type bool $featured
     *     @type bool $pinned
     *     @type bool $automatic
     *     @type \Eolymp\Ecm\Content $content
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $labels
     *     @type bool $unlabel
     *           clears the labels, which an empty list cannot express
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Content\Post::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string type_id = 6;</code>
     * @return string
     */
    public function getTypeId()
    {
        return isset($this->type_id) ? $this->type_id : '';
    }

    public function hasTypeId()
    {
        return isset($this->type_id);
    }

    public function clearTypeId()
    {
        unset($this->type_id);
    }

    /**
     * Generated from protobuf field <code>optional string type_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTypeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->type_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool featured = 9;</code>
     * @return bool
     */
    public function getFeatured()
    {
        return isset($this->featured) ? $this->featured : false;
    }

    public function hasFeatured()
    {
        return isset($this->featured);
    }

    public function clearFeatured()
    {
        unset($this->featured);
    }

    /**
     * Generated from protobuf field <code>optional bool featured = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setFeatured($var)
    {
        GPBUtil::checkBool($var);
        $this->featured = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool pinned = 13;</code>
     * @return bool
     */
    public function getPinned()
    {
        return isset($this->pinned) ? $this->pinned : false;
    }

    public function hasPinned()
    {
        return isset($this->pinned);
    }

    public function clearPinned()
    {
        unset($this->pinned);
    }

    /**
     * Generated from protobuf field <code>optional bool pinned = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setPinned($var)
    {
        GPBUtil::checkBool($var);
        $this->pinned = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool automatic = 14;</code>
     * @return bool
     */
    public function getAutomatic()
    {
        return isset($this->automatic) ? $this->automatic : false;
    }

    public function hasAutomatic()
    {
        return isset($this->automatic);
    }

    public function clearAutomatic()
    {
        unset($this->automatic);
    }

    /**
     * Generated from protobuf field <code>optional bool automatic = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setAutomatic($var)
    {
        GPBUtil::checkBool($var);
        $this->automatic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.ecm.Content content = 101;</code>
     * @return \Eolymp\Ecm\Content|null
     */
    public function getContent()
    {
        return $this->content;
    }

    public function hasContent()
    {
        return isset($this->content);
    }

    public function clearContent()
    {
        unset($this->content);
    }

    /**
     * Generated from protobuf field <code>.eolymp.ecm.Content content = 101;</code>
     * @param \Eolymp\Ecm\Content $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Ecm\Content::class);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string labels = 120;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * Generated from protobuf field <code>repeated string labels = 120;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->labels = $arr;

        return $this;
    }

    /**
     * clears the labels, which an empty list cannot express
     *
     * Generated from protobuf field <code>optional bool unlabel = 121;</code>
     * @return bool
     */
    public function getUnlabel()
    {
        return isset($this->unlabel) ? $this->unlabel : false;
    }

    public function hasUnlabel()
    {
        return isset($this->unlabel);
    }

    public function clearUnlabel()
    {
        unset($this->unlabel);
    }

    /**
     * clears the labels, which an empty list cannot express
     *
     * Generated from protobuf field <code>optional bool unlabel = 121;</code>
     * @param bool $var
     * @return $this
     */
    public function setUnlabel($var)
    {
        GPBUtil::checkBool($var);
        $this->unlabel = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Patch::class, \Eolymp\Content\Post_Patch::class);

