<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/judge/ticket_service.proto

namespace Eolymp\Judge\UpdateTicketInput;

use UnexpectedValueException;

/**
 * Protobuf type <code>eolymp.judge.UpdateTicketInput.Patch</code>
 */
class Patch
{
    /**
     * Generated from protobuf enum <code>ALL = 0;</code>
     */
    const ALL = 0;
    /**
     * Generated from protobuf enum <code>STATUS = 1;</code>
     */
    const STATUS = 1;
    /**
     * Generated from protobuf enum <code>SUBJECT = 2;</code>
     */
    const SUBJECT = 2;

    private static $valueToName = [
        self::ALL => 'ALL',
        self::STATUS => 'STATUS',
        self::SUBJECT => 'SUBJECT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

