<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/annotations/audit.proto

namespace Eolymp\Api\Audit;

use UnexpectedValueException;

/**
 * Protobuf type <code>eolymp.api.Audit.OperationType</code>
 */
class OperationType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_OPERATION_TYPE = 0;</code>
     */
    const UNKNOWN_OPERATION_TYPE = 0;
    /**
     * Generated from protobuf enum <code>READ = 1;</code>
     */
    const READ = 1;
    /**
     * Generated from protobuf enum <code>WRITE = 2;</code>
     */
    const WRITE = 2;
    /**
     * Generated from protobuf enum <code>DELETE = 3;</code>
     */
    const DELETE = 3;

    private static $valueToName = [
        self::UNKNOWN_OPERATION_TYPE => 'UNKNOWN_OPERATION_TYPE',
        self::READ => 'READ',
        self::WRITE => 'WRITE',
        self::DELETE => 'DELETE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(OperationType::class, \Eolymp\Api\Audit_OperationType::class);

