<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/commerce/checkout.proto

namespace Eolymp\Commerce\Checkout;

use UnexpectedValueException;

/**
 * Protobuf type <code>eolymp.commerce.Checkout.Mode</code>
 */
class Mode
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_MODE = 0;</code>
     */
    const UNKNOWN_MODE = 0;
    /**
     * Generated from protobuf enum <code>PAYMENT = 1;</code>
     */
    const PAYMENT = 1;
    /**
     * Generated from protobuf enum <code>SUBSCRIPTION = 2;</code>
     */
    const SUBSCRIPTION = 2;

    private static $valueToName = [
        self::UNKNOWN_MODE => 'UNKNOWN_MODE',
        self::PAYMENT => 'PAYMENT',
        self::SUBSCRIPTION => 'SUBSCRIPTION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Mode::class, \Eolymp\Commerce\Checkout_Mode::class);

