<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/scoreboard/scoreboard.proto

namespace Eolymp\Scoreboard;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Scoreboard\Scoreboard\Patch instead.
     * @deprecated
     */
    class Scoreboard_Patch {}
}
class_exists(Scoreboard\Patch::class);
@trigger_error('Eolymp\Scoreboard\Scoreboard_Patch is deprecated and will be removed in the next major release. Use Eolymp\Scoreboard\Scoreboard\Patch instead', E_USER_DEPRECATED);

