<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/scoreboard/scoreboard.proto

namespace Eolymp\Scoreboard;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Scoreboard\Scoreboard\Filter instead.
     * @deprecated
     */
    class Scoreboard_Filter {}
}
class_exists(Scoreboard\Filter::class);
@trigger_error('Eolymp\Scoreboard\Scoreboard_Filter is deprecated and will be removed in the next major release. Use Eolymp\Scoreboard\Scoreboard\Filter instead', E_USER_DEPRECATED);

