<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/scoreboard/scoreboard_service.proto

namespace Eolymp\Scoreboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.scoreboard.UpdateScoreboardInput</code>
 */
class UpdateScoreboardInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string scoreboard_id = 1;</code>
     */
    protected $scoreboard_id = '';
    /**
     * Generated from protobuf field <code>.eolymp.scoreboard.Scoreboard.Patch scoreboard = 3;</code>
     */
    protected $scoreboard = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $scoreboard_id
     *     @type \Eolymp\Scoreboard\Scoreboard\Patch $scoreboard
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Scoreboard\ScoreboardService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string scoreboard_id = 1;</code>
     * @return string
     */
    public function getScoreboardId()
    {
        return $this->scoreboard_id;
    }

    /**
     * Generated from protobuf field <code>string scoreboard_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setScoreboardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->scoreboard_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.scoreboard.Scoreboard.Patch scoreboard = 3;</code>
     * @return \Eolymp\Scoreboard\Scoreboard\Patch|null
     */
    public function getScoreboard()
    {
        return $this->scoreboard;
    }

    public function hasScoreboard()
    {
        return isset($this->scoreboard);
    }

    public function clearScoreboard()
    {
        unset($this->scoreboard);
    }

    /**
     * Generated from protobuf field <code>.eolymp.scoreboard.Scoreboard.Patch scoreboard = 3;</code>
     * @param \Eolymp\Scoreboard\Scoreboard\Patch $var
     * @return $this
     */
    public function setScoreboard($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Scoreboard\Scoreboard\Patch::class);
        $this->scoreboard = $var;

        return $this;
    }

}

