<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/judge/activity.proto

namespace Eolymp\Judge;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Judge\Activity\Status instead.
     * @deprecated
     */
    class Activity_Status {}
}
class_exists(Activity\Status::class);
@trigger_error('Eolymp\Judge\Activity_Status is deprecated and will be removed in the next major release. Use Eolymp\Judge\Activity\Status instead', E_USER_DEPRECATED);

