<?php
# Generated by the protocol buffer compiler. DO NOT EDIT!
# See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-php-esdk for more details.

namespace Eolymp\Judge;

class ContestSeriesServiceClient {

    /** @var string base URL */
    private $url;

    /** @var callable RPC client */
    private $invoker;

    /**
     * @param string   $url     defines base URL for service
     * @param callable $invoker provides transport implementation for calls
     */
    public function __construct($url, $invoker)
    {
        $this->url = $url;
        $this->invoker = $invoker;
    }

    /**
     * @param DescribeContestSeriesInput $input message
     * @param array $context request parameters
     *
     * @return DescribeContestSeriesOutput output message
     */
    public function DescribeContestSeries(DescribeContestSeriesInput $input, array $context = [])
    {
        $path = "/contest-series/".rawurlencode($input->getSeriesId());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setSeriesId("");

        $context['name'] = "eolymp.judge.ContestSeriesService/DescribeContestSeries";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, DescribeContestSeriesOutput::class, $context);
    }

    /**
     * @param ListContestSeriesInput $input message
     * @param array $context request parameters
     *
     * @return ListContestSeriesOutput output message
     */
    public function ListContestSeries(ListContestSeriesInput $input, array $context = [])
    {
        $path = "/contest-series";

        $context['name'] = "eolymp.judge.ContestSeriesService/ListContestSeries";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, ListContestSeriesOutput::class, $context);
    }

    /**
     * @param CreateContestSeriesInput $input message
     * @param array $context request parameters
     *
     * @return CreateContestSeriesOutput output message
     */
    public function CreateContestSeries(CreateContestSeriesInput $input, array $context = [])
    {
        $path = "/contest-series";

        $context['name'] = "eolymp.judge.ContestSeriesService/CreateContestSeries";
        $context['path'] = $path;

        return call_user_func($this->invoker, "POST", $this->url.$path, $input, CreateContestSeriesOutput::class, $context);
    }

    /**
     * @param UpdateContestSeriesInput $input message
     * @param array $context request parameters
     *
     * @return UpdateContestSeriesOutput output message
     */
    public function UpdateContestSeries(UpdateContestSeriesInput $input, array $context = [])
    {
        $path = "/contest-series/".rawurlencode($input->getSeriesId());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setSeriesId("");

        $context['name'] = "eolymp.judge.ContestSeriesService/UpdateContestSeries";
        $context['path'] = $path;

        return call_user_func($this->invoker, "PUT", $this->url.$path, $input, UpdateContestSeriesOutput::class, $context);
    }

    /**
     * @param DeleteContestSeriesInput $input message
     * @param array $context request parameters
     *
     * @return DeleteContestSeriesOutput output message
     */
    public function DeleteContestSeries(DeleteContestSeriesInput $input, array $context = [])
    {
        $path = "/contest-series/".rawurlencode($input->getSeriesId());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setSeriesId("");

        $context['name'] = "eolymp.judge.ContestSeriesService/DeleteContestSeries";
        $context['path'] = $path;

        return call_user_func($this->invoker, "DELETE", $this->url.$path, $input, DeleteContestSeriesOutput::class, $context);
    }

}
