<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/judge/judge.proto

namespace Eolymp\Judge;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Judge\ListScoreboardsInput\Filter instead.
     * @deprecated
     */
    class ListScoreboardsInput_Filter {}
}
class_exists(ListScoreboardsInput\Filter::class);
@trigger_error('Eolymp\Judge\ListScoreboardsInput_Filter is deprecated and will be removed in the next major release. Use Eolymp\Judge\ListScoreboardsInput\Filter instead', E_USER_DEPRECATED);

