<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/judge/judge.proto

namespace Eolymp\Judge;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.judge.LookupCodeTemplateOutput</code>
 */
class LookupCodeTemplateOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.eolymp.judge.Template template = 1;</code>
     */
    protected $template = null;
    /**
     * deprecated, use template instead
     *
     * Generated from protobuf field <code>.eolymp.judge.Template x_template = 100;</code>
     */
    protected $x_template = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Eolymp\Judge\Template $template
     *     @type \Eolymp\Judge\Template $x_template
     *           deprecated, use template instead
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Judge\Judge::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.eolymp.judge.Template template = 1;</code>
     * @return \Eolymp\Judge\Template
     */
    public function getTemplate()
    {
        return $this->template;
    }

    /**
     * Generated from protobuf field <code>.eolymp.judge.Template template = 1;</code>
     * @param \Eolymp\Judge\Template $var
     * @return $this
     */
    public function setTemplate($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Judge\Template::class);
        $this->template = $var;

        return $this;
    }

    /**
     * deprecated, use template instead
     *
     * Generated from protobuf field <code>.eolymp.judge.Template x_template = 100;</code>
     * @return \Eolymp\Judge\Template
     */
    public function getXTemplate()
    {
        return $this->x_template;
    }

    /**
     * deprecated, use template instead
     *
     * Generated from protobuf field <code>.eolymp.judge.Template x_template = 100;</code>
     * @param \Eolymp\Judge\Template $var
     * @return $this
     */
    public function setXTemplate($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Judge\Template::class);
        $this->x_template = $var;

        return $this;
    }

}

