<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/judge/score.proto

namespace Eolymp\Judge;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.judge.Score</code>
 */
class Score extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 offset = 1;</code>
     */
    protected $offset = 0;
    /**
     * Generated from protobuf field <code>float score = 10;</code>
     */
    protected $score = 0.0;
    /**
     * Generated from protobuf field <code>float penalty = 11;</code>
     */
    protected $penalty = 0.0;
    /**
     * breakdown of total score by problem
     *
     * Generated from protobuf field <code>repeated .eolymp.judge.Score.Problem breakdown = 20;</code>
     */
    private $breakdown;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $offset
     *     @type float $score
     *     @type float $penalty
     *     @type \Eolymp\Judge\Score\Problem[]|\Google\Protobuf\Internal\RepeatedField $breakdown
     *           breakdown of total score by problem
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Judge\Score::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 offset = 1;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>uint32 offset = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkUint32($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float score = 10;</code>
     * @return float
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>float score = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkFloat($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float penalty = 11;</code>
     * @return float
     */
    public function getPenalty()
    {
        return $this->penalty;
    }

    /**
     * Generated from protobuf field <code>float penalty = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setPenalty($var)
    {
        GPBUtil::checkFloat($var);
        $this->penalty = $var;

        return $this;
    }

    /**
     * breakdown of total score by problem
     *
     * Generated from protobuf field <code>repeated .eolymp.judge.Score.Problem breakdown = 20;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBreakdown()
    {
        return $this->breakdown;
    }

    /**
     * breakdown of total score by problem
     *
     * Generated from protobuf field <code>repeated .eolymp.judge.Score.Problem breakdown = 20;</code>
     * @param \Eolymp\Judge\Score\Problem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBreakdown($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eolymp\Judge\Score\Problem::class);
        $this->breakdown = $arr;

        return $this;
    }

}

