<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/guardian/guardian.proto

namespace Eolymp\Guardian;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.guardian.CreatePolicyOutput</code>
 */
class CreatePolicyOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string policy_id = 1;</code>
     */
    protected $policy_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $policy_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Guardian\Guardian::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string policy_id = 1;</code>
     * @return string
     */
    public function getPolicyId()
    {
        return $this->policy_id;
    }

    /**
     * Generated from protobuf field <code>string policy_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPolicyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->policy_id = $var;

        return $this;
    }

}

