<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/proctoring/recording_service.proto

namespace Eolymp\Proctoring;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.proctoring.ResumeRecordingOutput</code>
 */
class ResumeRecordingOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * WebSocket URL with a token to stream clips to
     *
     * Generated from protobuf field <code>string stream_url = 1;</code>
     */
    protected $stream_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stream_url
     *           WebSocket URL with a token to stream clips to
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Proctoring\RecordingService::initOnce();
        parent::__construct($data);
    }

    /**
     * WebSocket URL with a token to stream clips to
     *
     * Generated from protobuf field <code>string stream_url = 1;</code>
     * @return string
     */
    public function getStreamUrl()
    {
        return $this->stream_url;
    }

    /**
     * WebSocket URL with a token to stream clips to
     *
     * Generated from protobuf field <code>string stream_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStreamUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->stream_url = $var;

        return $this;
    }

}

