<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/keeper/blob.proto

namespace Eolymp\Keeper;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.keeper.Blob</code>
 */
class Blob extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ern = 1;</code>
     */
    protected $ern = '';
    /**
     * Unique identifier of the blob
     *
     * Generated from protobuf field <code>string key = 2;</code>
     */
    protected $key = '';
    /**
     * SHA1 hash of data
     *
     * Generated from protobuf field <code>string hash = 3;</code>
     */
    protected $hash = '';
    /**
     * Size of the data
     *
     * Generated from protobuf field <code>uint32 size = 4;</code>
     */
    protected $size = 0;
    /**
     * Generated from protobuf field <code>bytes data = 100;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ern
     *     @type string $key
     *           Unique identifier of the blob
     *     @type string $hash
     *           SHA1 hash of data
     *     @type int $size
     *           Size of the data
     *     @type string $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Keeper\Blob::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ern = 1;</code>
     * @return string
     */
    public function getErn()
    {
        return $this->ern;
    }

    /**
     * Generated from protobuf field <code>string ern = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setErn($var)
    {
        GPBUtil::checkString($var, True);
        $this->ern = $var;

        return $this;
    }

    /**
     * Unique identifier of the blob
     *
     * Generated from protobuf field <code>string key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Unique identifier of the blob
     *
     * Generated from protobuf field <code>string key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * SHA1 hash of data
     *
     * Generated from protobuf field <code>string hash = 3;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * SHA1 hash of data
     *
     * Generated from protobuf field <code>string hash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->hash = $var;

        return $this;
    }

    /**
     * Size of the data
     *
     * Generated from protobuf field <code>uint32 size = 4;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Size of the data
     *
     * Generated from protobuf field <code>uint32 size = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 100;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 100;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

