<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/community/member.proto

namespace Eolymp\Community\Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.community.Member.Stats</code>
 */
class Stats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 streak = 10;</code>
     */
    protected $streak = 0;
    /**
     * Generated from protobuf field <code>int32 problems_solved = 20;</code>
     */
    protected $problems_solved = 0;
    /**
     * Generated from protobuf field <code>int32 submissions_accepted = 30;</code>
     */
    protected $submissions_accepted = 0;
    /**
     * Generated from protobuf field <code>int32 submissions_total = 41;</code>
     */
    protected $submissions_total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $streak
     *     @type int $problems_solved
     *     @type int $submissions_accepted
     *     @type int $submissions_total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Community\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 streak = 10;</code>
     * @return int
     */
    public function getStreak()
    {
        return $this->streak;
    }

    /**
     * Generated from protobuf field <code>int32 streak = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setStreak($var)
    {
        GPBUtil::checkInt32($var);
        $this->streak = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 problems_solved = 20;</code>
     * @return int
     */
    public function getProblemsSolved()
    {
        return $this->problems_solved;
    }

    /**
     * Generated from protobuf field <code>int32 problems_solved = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setProblemsSolved($var)
    {
        GPBUtil::checkInt32($var);
        $this->problems_solved = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 submissions_accepted = 30;</code>
     * @return int
     */
    public function getSubmissionsAccepted()
    {
        return $this->submissions_accepted;
    }

    /**
     * Generated from protobuf field <code>int32 submissions_accepted = 30;</code>
     * @param int $var
     * @return $this
     */
    public function setSubmissionsAccepted($var)
    {
        GPBUtil::checkInt32($var);
        $this->submissions_accepted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 submissions_total = 41;</code>
     * @return int
     */
    public function getSubmissionsTotal()
    {
        return $this->submissions_total;
    }

    /**
     * Generated from protobuf field <code>int32 submissions_total = 41;</code>
     * @param int $var
     * @return $this
     */
    public function setSubmissionsTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->submissions_total = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Stats::class, \Eolymp\Community\Member_Stats::class);

