<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/judge/evidence.proto

namespace Eolymp\Judge\Evidence;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Session is a stretch of a participant's contest, for a finding about how it was worked through rather than
 * about what any one program says.
 *
 * Generated from protobuf message <code>eolymp.judge.Evidence.Session</code>
 */
class Session extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp from = 1;</code>
     */
    protected $from = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp to = 2;</code>
     */
    protected $to = null;
    /**
     * what this session did inside the window
     *
     * Generated from protobuf field <code>float value = 3;</code>
     */
    protected $value = 0.0;
    /**
     * what a typical session in this contest did
     *
     * Generated from protobuf field <code>float typical = 4;</code>
     */
    protected $typical = 0.0;
    /**
     * Generated from protobuf field <code>repeated .eolymp.judge.Evidence.Attempt attempts = 5;</code>
     */
    private $attempts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $from
     *     @type \Google\Protobuf\Timestamp $to
     *     @type float $value
     *           what this session did inside the window
     *     @type float $typical
     *           what a typical session in this contest did
     *     @type array<\Eolymp\Judge\Evidence\Attempt>|\Google\Protobuf\Internal\RepeatedField $attempts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Judge\Evidence::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp from = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getFrom()
    {
        return $this->from;
    }

    public function hasFrom()
    {
        return isset($this->from);
    }

    public function clearFrom()
    {
        unset($this->from);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp from = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp to = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTo()
    {
        return $this->to;
    }

    public function hasTo()
    {
        return isset($this->to);
    }

    public function clearTo()
    {
        unset($this->to);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp to = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->to = $var;

        return $this;
    }

    /**
     * what this session did inside the window
     *
     * Generated from protobuf field <code>float value = 3;</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * what this session did inside the window
     *
     * Generated from protobuf field <code>float value = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->value = $var;

        return $this;
    }

    /**
     * what a typical session in this contest did
     *
     * Generated from protobuf field <code>float typical = 4;</code>
     * @return float
     */
    public function getTypical()
    {
        return $this->typical;
    }

    /**
     * what a typical session in this contest did
     *
     * Generated from protobuf field <code>float typical = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setTypical($var)
    {
        GPBUtil::checkFloat($var);
        $this->typical = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.judge.Evidence.Attempt attempts = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttempts()
    {
        return $this->attempts;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.judge.Evidence.Attempt attempts = 5;</code>
     * @param array<\Eolymp\Judge\Evidence\Attempt>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttempts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eolymp\Judge\Evidence\Attempt::class);
        $this->attempts = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Session::class, \Eolymp\Judge\Evidence_Session::class);

