<?php
# Generated by the protocol buffer compiler. DO NOT EDIT!
# See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-php-esdk for more details.

namespace Eolymp\Workspace;

class WorkspaceClient {

    /** @var callable RPC client */
    private $invoker;

    /**
     * @param callable $invoker for RPC calls
     */
    public function __construct($invoker)
    {
        $this->invoker = $invoker;
    }

    /**
     * @param DescribeProjectInput $input message
     * @param array $context request parameters
     *
     * @return DescribeProjectOutput output message
     */
    public function DescribeProject(DescribeProjectInput $input, array $context = [])
    {
        return call_user_func($this->invoker, "eolymp.workspace.Workspace/DescribeProject", $input, DescribeProjectOutput::class, $context);
    }

    /**
     * @param ListProjectsInput $input message
     * @param array $context request parameters
     *
     * @return ListProjectsOutput output message
     */
    public function ListProjects(ListProjectsInput $input, array $context = [])
    {
        return call_user_func($this->invoker, "eolymp.workspace.Workspace/ListProjects", $input, ListProjectsOutput::class, $context);
    }

    /**
     * @param CreateProjectInput $input message
     * @param array $context request parameters
     *
     * @return CreateProjectOutput output message
     */
    public function CreateProject(CreateProjectInput $input, array $context = [])
    {
        return call_user_func($this->invoker, "eolymp.workspace.Workspace/CreateProject", $input, CreateProjectOutput::class, $context);
    }

    /**
     * @param UpdateProjectInput $input message
     * @param array $context request parameters
     *
     * @return UpdateProjectOutput output message
     */
    public function UpdateProject(UpdateProjectInput $input, array $context = [])
    {
        return call_user_func($this->invoker, "eolymp.workspace.Workspace/UpdateProject", $input, UpdateProjectOutput::class, $context);
    }

    /**
     * @param DeleteProjectInput $input message
     * @param array $context request parameters
     *
     * @return DeleteProjectOutput output message
     */
    public function DeleteProject(DeleteProjectInput $input, array $context = [])
    {
        return call_user_func($this->invoker, "eolymp.workspace.Workspace/DeleteProject", $input, DeleteProjectOutput::class, $context);
    }

    /**
     * @param ListFilesInput $input message
     * @param array $context request parameters
     *
     * @return ListFilesOutput output message
     */
    public function ListFiles(ListFilesInput $input, array $context = [])
    {
        return call_user_func($this->invoker, "eolymp.workspace.Workspace/ListFiles", $input, ListFilesOutput::class, $context);
    }

    /**
     * @param DescribeFileInput $input message
     * @param array $context request parameters
     *
     * @return DescribeFileOutput output message
     */
    public function DescribeFile(DescribeFileInput $input, array $context = [])
    {
        return call_user_func($this->invoker, "eolymp.workspace.Workspace/DescribeFile", $input, DescribeFileOutput::class, $context);
    }

    /**
     * @param UploadFileInput $input message
     * @param array $context request parameters
     *
     * @return UploadFileOutput output message
     */
    public function UploadFile(UploadFileInput $input, array $context = [])
    {
        return call_user_func($this->invoker, "eolymp.workspace.Workspace/UploadFile", $input, UploadFileOutput::class, $context);
    }

    /**
     * @param RemoveFileInput $input message
     * @param array $context request parameters
     *
     * @return RemoveFileOutput output message
     */
    public function RemoveFile(RemoveFileInput $input, array $context = [])
    {
        return call_user_func($this->invoker, "eolymp.workspace.Workspace/RemoveFile", $input, RemoveFileOutput::class, $context);
    }

}
