<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/automation/action.proto

namespace Eolymp\Automation\Action;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.automation.Action.AgenticAction</code>
 */
class AgenticAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string instructions = 1;</code>
     */
    protected $instructions = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $instructions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Automation\Action::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string instructions = 1;</code>
     * @return string
     */
    public function getInstructions()
    {
        return $this->instructions;
    }

    /**
     * Generated from protobuf field <code>string instructions = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInstructions($var)
    {
        GPBUtil::checkString($var, True);
        $this->instructions = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AgenticAction::class, \Eolymp\Automation\Action_AgenticAction::class);

