<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/course/assignment.proto

namespace Eolymp\Course;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Course\Assignment\Status instead.
     * @deprecated
     */
    class Assignment_Status {}
}
class_exists(Assignment\Status::class);
@trigger_error('Eolymp\Course\Assignment_Status is deprecated and will be removed in the next major release. Use Eolymp\Course\Assignment\Status instead', E_USER_DEPRECATED);

