<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/course/assignment_service.proto

namespace Eolymp\Course;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Course\ListAssignmentsInput\Sortable instead.
     * @deprecated
     */
    class ListAssignmentsInput_Sortable {}
}
class_exists(ListAssignmentsInput\Sortable::class);
@trigger_error('Eolymp\Course\ListAssignmentsInput_Sortable is deprecated and will be removed in the next major release. Use Eolymp\Course\ListAssignmentsInput\Sortable instead', E_USER_DEPRECATED);

