<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/course/assignment_service.proto

namespace Eolymp\Course;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.course.UnassignAssignmentInput</code>
 */
class UnassignAssignmentInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string assignment_id = 1;</code>
     */
    protected $assignment_id = '';
    /**
     * Generated from protobuf field <code>string student_id = 2;</code>
     */
    protected $student_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $assignment_id
     *     @type string $student_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Course\AssignmentService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string assignment_id = 1;</code>
     * @return string
     */
    public function getAssignmentId()
    {
        return $this->assignment_id;
    }

    /**
     * Generated from protobuf field <code>string assignment_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAssignmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->assignment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string student_id = 2;</code>
     * @return string
     */
    public function getStudentId()
    {
        return $this->student_id;
    }

    /**
     * Generated from protobuf field <code>string student_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStudentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->student_id = $var;

        return $this;
    }

}

