<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/course/module_service.proto

namespace Eolymp\Course;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Course\UpdateModuleInput\Patch instead.
     * @deprecated
     */
    class UpdateModuleInput_Patch {}
}
class_exists(UpdateModuleInput\Patch::class);
@trigger_error('Eolymp\Course\UpdateModuleInput_Patch is deprecated and will be removed in the next major release. Use Eolymp\Course\UpdateModuleInput\Patch instead', E_USER_DEPRECATED);

