<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/course/editor_service.proto

namespace Eolymp\Course;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.course.UpdateEditorStateInput</code>
 */
class UpdateEditorStateInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string course_id = 1;</code>
     */
    protected $course_id = '';
    /**
     * Generated from protobuf field <code>string material_id = 2;</code>
     */
    protected $material_id = '';
    /**
     * Generated from protobuf field <code>string runtime = 3;</code>
     */
    protected $runtime = '';
    /**
     * Generated from protobuf field <code>string source_code = 4;</code>
     */
    protected $source_code = '';
    /**
     * Generated from protobuf field <code>string input_data = 5;</code>
     */
    protected $input_data = '';
    protected $payload;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $course_id
     *     @type string $material_id
     *     @type string $runtime
     *     @type string $source_code
     *     @type string $input_data
     *     @type \Eolymp\Atlas\Submission\Output $output
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Course\EditorService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string course_id = 1;</code>
     * @return string
     */
    public function getCourseId()
    {
        return $this->course_id;
    }

    /**
     * Generated from protobuf field <code>string course_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCourseId($var)
    {
        GPBUtil::checkString($var, True);
        $this->course_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string material_id = 2;</code>
     * @return string
     */
    public function getMaterialId()
    {
        return $this->material_id;
    }

    /**
     * Generated from protobuf field <code>string material_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMaterialId($var)
    {
        GPBUtil::checkString($var, True);
        $this->material_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string runtime = 3;</code>
     * @return string
     */
    public function getRuntime()
    {
        return $this->runtime;
    }

    /**
     * Generated from protobuf field <code>string runtime = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRuntime($var)
    {
        GPBUtil::checkString($var, True);
        $this->runtime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_code = 4;</code>
     * @return string
     */
    public function getSourceCode()
    {
        return $this->source_code;
    }

    /**
     * Generated from protobuf field <code>string source_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string input_data = 5;</code>
     * @return string
     */
    public function getInputData()
    {
        return $this->input_data;
    }

    /**
     * Generated from protobuf field <code>string input_data = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setInputData($var)
    {
        GPBUtil::checkString($var, True);
        $this->input_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Submission.Output output = 6;</code>
     * @return \Eolymp\Atlas\Submission\Output|null
     */
    public function getOutput()
    {
        return $this->readOneof(6);
    }

    public function hasOutput()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.eolymp.atlas.Submission.Output output = 6;</code>
     * @param \Eolymp\Atlas\Submission\Output $var
     * @return $this
     */
    public function setOutput($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Atlas\Submission\Output::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getPayload()
    {
        return $this->whichOneof("payload");
    }

}

