<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/proctoring/recording.proto

namespace Eolymp\Proctoring\Recording;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.proctoring.Recording.Stream</code>
 */
class Stream extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.eolymp.proctoring.Recording.Stream.Source source = 1;</code>
     */
    protected $source = 0;
    /**
     * HLS playlist, requires proctoring:recording:read
     *
     * Generated from protobuf field <code>string playlist_url = 2;</code>
     */
    protected $playlist_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $source
     *     @type string $playlist_url
     *           HLS playlist, requires proctoring:recording:read
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Proctoring\Recording::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.eolymp.proctoring.Recording.Stream.Source source = 1;</code>
     * @return int
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>.eolymp.proctoring.Recording.Stream.Source source = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkEnum($var, \Eolymp\Proctoring\Recording\Stream\Source::class);
        $this->source = $var;

        return $this;
    }

    /**
     * HLS playlist, requires proctoring:recording:read
     *
     * Generated from protobuf field <code>string playlist_url = 2;</code>
     * @return string
     */
    public function getPlaylistUrl()
    {
        return $this->playlist_url;
    }

    /**
     * HLS playlist, requires proctoring:recording:read
     *
     * Generated from protobuf field <code>string playlist_url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaylistUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->playlist_url = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Stream::class, \Eolymp\Proctoring\Recording_Stream::class);

