<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/universe/auth.proto

namespace Eolymp\Universe;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Universe\Authentication\OAuth2 instead.
     * @deprecated
     */
    class Authentication_OAuth2 {}
}
class_exists(Authentication\OAuth2::class);
@trigger_error('Eolymp\Universe\Authentication_OAuth2 is deprecated and will be removed in the next major release. Use Eolymp\Universe\Authentication\OAuth2 instead', E_USER_DEPRECATED);

