<?php
# Generated by the protocol buffer compiler. DO NOT EDIT!
# See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-php-esdk for more details.

namespace Eolymp\Universe;

class NotificationServiceClient {

    /** @var string base URL */
    private $url;

    /** @var callable RPC client */
    private $invoker;

    /**
     * @param string   $url     defines base URL for service
     * @param callable $invoker provides transport implementation for calls
     */
    public function __construct($url, $invoker)
    {
        $this->url = $url;
        $this->invoker = $invoker;
    }

    /**
     * @param DescribeNotificationInput $input message
     * @param array $context request parameters
     *
     * @return DescribeNotificationOutput output message
     */
    public function DescribeNotification(DescribeNotificationInput $input, array $context = [])
    {
        $path = "/notifications/".rawurlencode($input->getNotification());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setNotification("");

        $context['name'] = "eolymp.universe.NotificationService/DescribeNotification";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, DescribeNotificationOutput::class, $context);
    }

    /**
     * @param ReadNotificationInput $input message
     * @param array $context request parameters
     *
     * @return ReadNotificationOutput output message
     */
    public function ReadNotification(ReadNotificationInput $input, array $context = [])
    {
        $path = "/notifications/".rawurlencode($input->getNotification())."/read";

        // Cleanup URL parameters to avoid any ambiguity
        $input->setNotification("");

        $context['name'] = "eolymp.universe.NotificationService/ReadNotification";
        $context['path'] = $path;

        return call_user_func($this->invoker, "POST", $this->url.$path, $input, ReadNotificationOutput::class, $context);
    }

    /**
     * @param DeleteNotificationInput $input message
     * @param array $context request parameters
     *
     * @return DeleteNotificationOutput output message
     */
    public function DeleteNotification(DeleteNotificationInput $input, array $context = [])
    {
        $path = "/notifications/".rawurlencode($input->getNotification());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setNotification("");

        $context['name'] = "eolymp.universe.NotificationService/DeleteNotification";
        $context['path'] = $path;

        return call_user_func($this->invoker, "DELETE", $this->url.$path, $input, DeleteNotificationOutput::class, $context);
    }

    /**
     * @param ListNotificationsInput $input message
     * @param array $context request parameters
     *
     * @return ListNotificationsOutput output message
     */
    public function ListNotifications(ListNotificationsInput $input, array $context = [])
    {
        $path = "/notifications";

        $context['name'] = "eolymp.universe.NotificationService/ListNotifications";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, ListNotificationsOutput::class, $context);
    }

    /**
     * @param DescribeNotificationConfigInput $input message
     * @param array $context request parameters
     *
     * @return DescribeNotificationConfigOutput output message
     */
    public function DescribeNotificationConfig(DescribeNotificationConfigInput $input, array $context = [])
    {
        $path = "/configs/notifications";

        $context['name'] = "eolymp.universe.NotificationService/DescribeNotificationConfig";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, DescribeNotificationConfigOutput::class, $context);
    }

    /**
     * @param UpdateNotificationConfigInput $input message
     * @param array $context request parameters
     *
     * @return UpdateNotificationConfigOutput output message
     */
    public function UpdateNotificationConfig(UpdateNotificationConfigInput $input, array $context = [])
    {
        $path = "/configs/notifications";

        $context['name'] = "eolymp.universe.NotificationService/UpdateNotificationConfig";
        $context['path'] = $path;

        return call_user_func($this->invoker, "POST", $this->url.$path, $input, UpdateNotificationConfigOutput::class, $context);
    }

}
