<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/universe/billing_service.proto

namespace Eolymp\Universe;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.universe.PayInvoiceInput</code>
 */
class PayInvoiceInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string invoice_id = 1;</code>
     */
    protected $invoice_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $invoice_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Universe\BillingService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string invoice_id = 1;</code>
     * @return string
     */
    public function getInvoiceId()
    {
        return $this->invoice_id;
    }

    /**
     * Generated from protobuf field <code>string invoice_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->invoice_id = $var;

        return $this;
    }

}

