<?php
# Generated by the protocol buffer compiler. DO NOT EDIT!
# See https://github.com/eolymp/contracts/tree/main/cmd/protoc-gen-php-esdk for more details.

namespace Eolymp\Universe;

class PlanServiceClient {

    /** @var string base URL */
    private $url;

    /** @var callable RPC client */
    private $invoker;

    /**
     * @param string   $url     defines base URL for service
     * @param callable $invoker provides transport implementation for calls
     */
    public function __construct($url, $invoker)
    {
        $this->url = $url;
        $this->invoker = $invoker;
    }

    /**
     * @param DescribePlanInput $input message
     * @param array $context request parameters
     *
     * @return DescribePlanOutput output message
     */
    public function DescribePlan(DescribePlanInput $input, array $context = [])
    {
        $path = "/plans/".rawurlencode($input->getPlanId());

        // Cleanup URL parameters to avoid any ambiguity
        $input->setPlanId("");

        $context['name'] = "eolymp.universe.PlanService/DescribePlan";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, DescribePlanOutput::class, $context);
    }

    /**
     * @param ListPlansInput $input message
     * @param array $context request parameters
     *
     * @return ListPlansOutput output message
     */
    public function ListPlans(ListPlansInput $input, array $context = [])
    {
        $path = "/plans";

        $context['name'] = "eolymp.universe.PlanService/ListPlans";
        $context['path'] = $path;

        return call_user_func($this->invoker, "GET", $this->url.$path, $input, ListPlansOutput::class, $context);
    }

}
