<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/universe/events.proto

namespace Eolymp\Universe;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QuotaChangedEvent is emitted when the quota a space runs under changes, which happens when its subscription
 * changes plan or lapses. Editing a plan or a space quota by hand does not emit it.
 *
 * Generated from protobuf message <code>eolymp.universe.QuotaChangedEvent</code>
 */
class QuotaChangedEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string space_id = 1;</code>
     */
    protected $space_id = '';
    /**
     * Generated from protobuf field <code>.eolymp.universe.Quota before = 2;</code>
     */
    protected $before = null;
    /**
     * Generated from protobuf field <code>.eolymp.universe.Quota after = 3;</code>
     */
    protected $after = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $space_id
     *     @type \Eolymp\Universe\Quota $before
     *     @type \Eolymp\Universe\Quota $after
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Universe\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string space_id = 1;</code>
     * @return string
     */
    public function getSpaceId()
    {
        return $this->space_id;
    }

    /**
     * Generated from protobuf field <code>string space_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpaceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->space_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.universe.Quota before = 2;</code>
     * @return \Eolymp\Universe\Quota|null
     */
    public function getBefore()
    {
        return $this->before;
    }

    public function hasBefore()
    {
        return isset($this->before);
    }

    public function clearBefore()
    {
        unset($this->before);
    }

    /**
     * Generated from protobuf field <code>.eolymp.universe.Quota before = 2;</code>
     * @param \Eolymp\Universe\Quota $var
     * @return $this
     */
    public function setBefore($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Universe\Quota::class);
        $this->before = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.universe.Quota after = 3;</code>
     * @return \Eolymp\Universe\Quota|null
     */
    public function getAfter()
    {
        return $this->after;
    }

    public function hasAfter()
    {
        return isset($this->after);
    }

    public function clearAfter()
    {
        unset($this->after);
    }

    /**
     * Generated from protobuf field <code>.eolymp.universe.Quota after = 3;</code>
     * @param \Eolymp\Universe\Quota $var
     * @return $this
     */
    public function setAfter($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Universe\Quota::class);
        $this->after = $var;

        return $this;
    }

}

