<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/guardian/guardian.proto

namespace Eolymp\Universe;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.universe.RemovePolicyOutput</code>
 */
class RemovePolicyOutput extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Guardian\Guardian::initOnce();
        parent::__construct($data);
    }

}

