<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/guardian/policy.proto

namespace Eolymp\Universe;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Universe\Statement\Effect instead.
     * @deprecated
     */
    class Statement_Effect {}
}
class_exists(Statement\Effect::class);
@trigger_error('Eolymp\Universe\Statement_Effect is deprecated and will be removed in the next major release. Use Eolymp\Universe\Statement\Effect instead', E_USER_DEPRECATED);

