<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/executor/checker.proto

namespace Eolymp\Executor;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Executor\Checker\Lines instead.
     * @deprecated
     */
    class Checker_Lines {}
}
class_exists(Checker\Lines::class);
@trigger_error('Eolymp\Executor\Checker_Lines is deprecated and will be removed in the next major release. Use Eolymp\Executor\Checker\Lines instead', E_USER_DEPRECATED);

