<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/executor/run_service.proto

namespace Eolymp\Executor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.executor.CreateRunInput</code>
 */
class CreateRunInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.eolymp.executor.CreateRunInput.Program program = 1;</code>
     */
    protected $program = null;
    /**
     * Generated from protobuf field <code>repeated string arguments = 2;</code>
     */
    private $arguments;
    /**
     * optional, the program talks to it instead of reading input directly
     *
     * Generated from protobuf field <code>.eolymp.executor.CreateRunInput.Program interactor = 3;</code>
     */
    protected $interactor = null;
    /**
     * milliseconds
     *
     * Generated from protobuf field <code>uint32 wall_time_limit = 20;</code>
     */
    protected $wall_time_limit = 0;
    /**
     * milliseconds
     *
     * Generated from protobuf field <code>uint32 cpu_time_limit = 21;</code>
     */
    protected $cpu_time_limit = 0;
    /**
     * bytes
     *
     * Generated from protobuf field <code>uint64 memory_limit = 22;</code>
     */
    protected $memory_limit = 0;
    protected $input;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Eolymp\Executor\CreateRunInput\Program $program
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $arguments
     *     @type \Eolymp\Executor\CreateRunInput\Program $interactor
     *           optional, the program talks to it instead of reading input directly
     *     @type string $input_url
     *     @type string $input_content
     *     @type int $wall_time_limit
     *           milliseconds
     *     @type int $cpu_time_limit
     *           milliseconds
     *     @type int|string $memory_limit
     *           bytes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Executor\RunService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.eolymp.executor.CreateRunInput.Program program = 1;</code>
     * @return \Eolymp\Executor\CreateRunInput\Program|null
     */
    public function getProgram()
    {
        return $this->program;
    }

    public function hasProgram()
    {
        return isset($this->program);
    }

    public function clearProgram()
    {
        unset($this->program);
    }

    /**
     * Generated from protobuf field <code>.eolymp.executor.CreateRunInput.Program program = 1;</code>
     * @param \Eolymp\Executor\CreateRunInput\Program $var
     * @return $this
     */
    public function setProgram($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Executor\CreateRunInput\Program::class);
        $this->program = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string arguments = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArguments()
    {
        return $this->arguments;
    }

    /**
     * Generated from protobuf field <code>repeated string arguments = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArguments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->arguments = $arr;

        return $this;
    }

    /**
     * optional, the program talks to it instead of reading input directly
     *
     * Generated from protobuf field <code>.eolymp.executor.CreateRunInput.Program interactor = 3;</code>
     * @return \Eolymp\Executor\CreateRunInput\Program|null
     */
    public function getInteractor()
    {
        return $this->interactor;
    }

    public function hasInteractor()
    {
        return isset($this->interactor);
    }

    public function clearInteractor()
    {
        unset($this->interactor);
    }

    /**
     * optional, the program talks to it instead of reading input directly
     *
     * Generated from protobuf field <code>.eolymp.executor.CreateRunInput.Program interactor = 3;</code>
     * @param \Eolymp\Executor\CreateRunInput\Program $var
     * @return $this
     */
    public function setInteractor($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Executor\CreateRunInput\Program::class);
        $this->interactor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string input_url = 10;</code>
     * @return string
     */
    public function getInputUrl()
    {
        return $this->readOneof(10);
    }

    public function hasInputUrl()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>string input_url = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setInputUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string input_content = 11;</code>
     * @return string
     */
    public function getInputContent()
    {
        return $this->readOneof(11);
    }

    public function hasInputContent()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>string input_content = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setInputContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * milliseconds
     *
     * Generated from protobuf field <code>uint32 wall_time_limit = 20;</code>
     * @return int
     */
    public function getWallTimeLimit()
    {
        return $this->wall_time_limit;
    }

    /**
     * milliseconds
     *
     * Generated from protobuf field <code>uint32 wall_time_limit = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setWallTimeLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->wall_time_limit = $var;

        return $this;
    }

    /**
     * milliseconds
     *
     * Generated from protobuf field <code>uint32 cpu_time_limit = 21;</code>
     * @return int
     */
    public function getCpuTimeLimit()
    {
        return $this->cpu_time_limit;
    }

    /**
     * milliseconds
     *
     * Generated from protobuf field <code>uint32 cpu_time_limit = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setCpuTimeLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->cpu_time_limit = $var;

        return $this;
    }

    /**
     * bytes
     *
     * Generated from protobuf field <code>uint64 memory_limit = 22;</code>
     * @return int|string
     */
    public function getMemoryLimit()
    {
        return $this->memory_limit;
    }

    /**
     * bytes
     *
     * Generated from protobuf field <code>uint64 memory_limit = 22;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemoryLimit($var)
    {
        GPBUtil::checkUint64($var);
        $this->memory_limit = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getInput()
    {
        return $this->whichOneof("input");
    }

}

