<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/executor/interactor.proto

namespace Eolymp\Executor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Interactor provides configuration for program which would interact with task during execution
 *
 * Generated from protobuf message <code>eolymp.executor.Interactor</code>
 */
class Interactor extends \Google\Protobuf\Internal\Message
{
    /**
     * Programming language in which interactor is written
     *
     * Generated from protobuf field <code>string lang = 1;</code>
     */
    protected $lang = '';
    /**
     * Source code for interactor
     *
     * Generated from protobuf field <code>string source = 2;</code>
     */
    protected $source = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $lang
     *           Programming language in which interactor is written
     *     @type string $source
     *           Source code for interactor
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Executor\Interactor::initOnce();
        parent::__construct($data);
    }

    /**
     * Programming language in which interactor is written
     *
     * Generated from protobuf field <code>string lang = 1;</code>
     * @return string
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     * Programming language in which interactor is written
     *
     * Generated from protobuf field <code>string lang = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLang($var)
    {
        GPBUtil::checkString($var, True);
        $this->lang = $var;

        return $this;
    }

    /**
     * Source code for interactor
     *
     * Generated from protobuf field <code>string source = 2;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Source code for interactor
     *
     * Generated from protobuf field <code>string source = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

}

