<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/executor/job.proto

namespace Eolymp\Executor;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Executor\Job\File instead.
     * @deprecated
     */
    class Job_File {}
}
class_exists(Job\File::class);
@trigger_error('Eolymp\Executor\Job_File is deprecated and will be removed in the next major release. Use Eolymp\Executor\Job\File instead', E_USER_DEPRECATED);

