<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/executor/executor.proto

namespace Eolymp\Executor;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Executor\ListRuntimeInput\Filter instead.
     * @deprecated
     */
    class ListRuntimeInput_Filter {}
}
class_exists(ListRuntimeInput\Filter::class);
@trigger_error('Eolymp\Executor\ListRuntimeInput_Filter is deprecated and will be removed in the next major release. Use Eolymp\Executor\ListRuntimeInput\Filter instead', E_USER_DEPRECATED);

