<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/executor/status_v2.proto

namespace Eolymp\Executor;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Executor\StatusV2\Actor instead.
     * @deprecated
     */
    class StatusV2_Actor {}
}
class_exists(StatusV2\Actor::class);
@trigger_error('Eolymp\Executor\StatusV2_Actor is deprecated and will be removed in the next major release. Use Eolymp\Executor\StatusV2\Actor instead', E_USER_DEPRECATED);

