<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/executor/status.proto

namespace Eolymp\Executor;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Executor\Status\Run instead.
     * @deprecated
     */
    class Status_Run {}
}
class_exists(Status\Run::class);
@trigger_error('Eolymp\Executor\Status_Run is deprecated and will be removed in the next major release. Use Eolymp\Executor\Status\Run instead', E_USER_DEPRECATED);

