<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/taxonomy/enum.proto

namespace GPBMetadata\Eolymp\Taxonomy;

class Enum
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Œ
eolymp/taxonomy/enum.protoeolymp.taxonomy" 
Enum

id (	
name (	B3Z1github.com/eolymp/go-sdk/eolymp/taxonomy;taxonomybproto3'
        , true);

        static::$is_initialized = true;
    }
}

