<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/rating/rating_service.proto

namespace Eolymp\Rating;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.rating.DescribeRatingOutput</code>
 */
class DescribeRatingOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.eolymp.rating.Rating point = 1;</code>
     */
    protected $point = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Eolymp\Rating\Rating $point
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Rating\RatingService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.eolymp.rating.Rating point = 1;</code>
     * @return \Eolymp\Rating\Rating|null
     */
    public function getPoint()
    {
        return $this->point;
    }

    public function hasPoint()
    {
        return isset($this->point);
    }

    public function clearPoint()
    {
        unset($this->point);
    }

    /**
     * Generated from protobuf field <code>.eolymp.rating.Rating point = 1;</code>
     * @param \Eolymp\Rating\Rating $var
     * @return $this
     */
    public function setPoint($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Rating\Rating::class);
        $this->point = $var;

        return $this;
    }

}

