<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/ranker/scoreboard.proto

namespace Eolymp\Ranker;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Ranker\Scoreboard\Row\Score instead.
     * @deprecated
     */
    class Scoreboard_Row_Score {}
}
class_exists(Scoreboard\Row\Score::class);
@trigger_error('Eolymp\Ranker\Scoreboard_Row_Score is deprecated and will be removed in the next major release. Use Eolymp\Ranker\Scoreboard\Row\Score instead', E_USER_DEPRECATED);

