<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/ranker/scoreboard.proto

namespace Eolymp\Ranker;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Ranker\Scoreboard\Extra instead.
     * @deprecated
     */
    class Scoreboard_Extra {}
}
class_exists(Scoreboard\Extra::class);
@trigger_error('Eolymp\Ranker\Scoreboard_Extra is deprecated and will be removed in the next major release. Use Eolymp\Ranker\Scoreboard\Extra instead', E_USER_DEPRECATED);

