<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/judge/contest.proto

namespace Eolymp\Judge\Contest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>eolymp.judge.Contest.EnvironmentConfig</code>
 */
class EnvironmentConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .eolymp.runtime.Runtime runtimes = 2;</code>
     */
    private $runtimes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Eolymp\Runtime\Runtime[] $runtimes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Judge\Contest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.runtime.Runtime runtimes = 2;</code>
     * @return RepeatedField<\Eolymp\Runtime\Runtime>
     */
    public function getRuntimes()
    {
        return $this->runtimes;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.runtime.Runtime runtimes = 2;</code>
     * @param \Eolymp\Runtime\Runtime[] $var
     * @return $this
     */
    public function setRuntimes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eolymp\Runtime\Runtime::class);
        $this->runtimes = $arr;

        return $this;
    }

}

