<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/judge/contest.proto

namespace Eolymp\Judge\Contest\Extra;

use UnexpectedValueException;

/**
 * Protobuf type <code>eolymp.judge.Contest.Extra.Field</code>
 */
class Field
{
    /**
     * reserved, should not be used
     *
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>CLASSIFICATION = 1;</code>
     */
    const CLASSIFICATION = 1;
    /**
     * Generated from protobuf enum <code>SCOREBOARD_CONFIG = 2;</code>
     */
    const SCOREBOARD_CONFIG = 2;
    /**
     * Generated from protobuf enum <code>CERTIFICATION_CONFIG = 3;</code>
     */
    const CERTIFICATION_CONFIG = 3;
    /**
     * Generated from protobuf enum <code>ENVIRONMENT_CONFIG = 4;</code>
     */
    const ENVIRONMENT_CONFIG = 4;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::CLASSIFICATION => 'CLASSIFICATION',
        self::SCOREBOARD_CONFIG => 'SCOREBOARD_CONFIG',
        self::CERTIFICATION_CONFIG => 'CERTIFICATION_CONFIG',
        self::ENVIRONMENT_CONFIG => 'ENVIRONMENT_CONFIG',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

