<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/universe/plan.proto

namespace Eolymp\Universe\Plan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.universe.Plan.Variant</code>
 */
class Variant extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.eolymp.universe.Plan.Recurrence recurrence = 3;</code>
     */
    protected $recurrence = 0;
    /**
     * Generated from protobuf field <code>string currency = 30;</code>
     */
    protected $currency = '';
    /**
     * Generated from protobuf field <code>uint32 unit_amount = 31;</code>
     */
    protected $unit_amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type int $recurrence
     *     @type string $currency
     *     @type int $unit_amount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Universe\Plan::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.universe.Plan.Recurrence recurrence = 3;</code>
     * @return int
     */
    public function getRecurrence()
    {
        return $this->recurrence;
    }

    /**
     * Generated from protobuf field <code>.eolymp.universe.Plan.Recurrence recurrence = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRecurrence($var)
    {
        GPBUtil::checkEnum($var, \Eolymp\Universe\Plan_Recurrence::class);
        $this->recurrence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 30;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 unit_amount = 31;</code>
     * @return int
     */
    public function getUnitAmount()
    {
        return $this->unit_amount;
    }

    /**
     * Generated from protobuf field <code>uint32 unit_amount = 31;</code>
     * @param int $var
     * @return $this
     */
    public function setUnitAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->unit_amount = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Variant::class, \Eolymp\Universe\Plan_Variant::class);

