<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/commerce/invoice.proto

namespace Eolymp\Commerce;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Commerce\Invoice\Item instead.
     * @deprecated
     */
    class Invoice_Item {}
}
class_exists(Invoice\Item::class);
@trigger_error('Eolymp\Commerce\Invoice_Item is deprecated and will be removed in the next major release. Use Eolymp\Commerce\Invoice\Item instead', E_USER_DEPRECATED);

