<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/commerce/order.proto

namespace Eolymp\Commerce;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Order represents a finalized and submitted shopping cart.
 * All amounts are specified in cents, for example 100 means €1.
 *
 * Generated from protobuf message <code>eolymp.commerce.Order</code>
 */
class Order extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string reference = 2;</code>
     */
    protected $reference = '';
    /**
     * Generated from protobuf field <code>.eolymp.commerce.Order.Status status = 3;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>repeated .eolymp.commerce.Order.Item items = 10;</code>
     */
    private $items;
    /**
     * Generated from protobuf field <code>.eolymp.commerce.Address billing_address = 40;</code>
     */
    protected $billing_address = null;
    /**
     * Generated from protobuf field <code>.eolymp.commerce.Address shipping_address = 41;</code>
     */
    protected $shipping_address = null;
    /**
     * Generated from protobuf field <code>bool billing_same_as_shipping = 42;</code>
     */
    protected $billing_same_as_shipping = false;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp estimated_shipping_date = 45;</code>
     */
    protected $estimated_shipping_date = null;
    /**
     * Generated from protobuf field <code>string currency = 20;</code>
     */
    protected $currency = '';
    /**
     * Generated from protobuf field <code>uint32 total_amount = 21;</code>
     */
    protected $total_amount = 0;
    /**
     * Generated from protobuf field <code>uint32 shipping_amount = 22;</code>
     */
    protected $shipping_amount = 0;
    /**
     * Generated from protobuf field <code>uint32 discount_amount = 23;</code>
     */
    protected $discount_amount = 0;
    /**
     * Generated from protobuf field <code>uint32 tax_amount = 24;</code>
     */
    protected $tax_amount = 0;
    /**
     * in hundredth of percent, e.g. 755 means 7.55%
     *
     * Generated from protobuf field <code>uint32 tax_rate = 25;</code>
     */
    protected $tax_rate = 0;
    /**
     * Generated from protobuf field <code>string tax_note = 26;</code>
     */
    protected $tax_note = '';
    /**
     * Generated from protobuf field <code>uint32 grand_total = 30;</code>
     */
    protected $grand_total = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 100;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 101;</code>
     */
    protected $updated_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $reference
     *     @type int $status
     *     @type array<\Eolymp\Commerce\Order\Item>|\Google\Protobuf\Internal\RepeatedField $items
     *     @type \Eolymp\Commerce\Address $billing_address
     *     @type \Eolymp\Commerce\Address $shipping_address
     *     @type bool $billing_same_as_shipping
     *     @type \Google\Protobuf\Timestamp $estimated_shipping_date
     *     @type string $currency
     *     @type int $total_amount
     *     @type int $shipping_amount
     *     @type int $discount_amount
     *     @type int $tax_amount
     *     @type int $tax_rate
     *           in hundredth of percent, e.g. 755 means 7.55%
     *     @type string $tax_note
     *     @type int $grand_total
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Commerce\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reference = 2;</code>
     * @return string
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * Generated from protobuf field <code>string reference = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReference($var)
    {
        GPBUtil::checkString($var, True);
        $this->reference = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.commerce.Order.Status status = 3;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.eolymp.commerce.Order.Status status = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Eolymp\Commerce\Order\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.commerce.Order.Item items = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.commerce.Order.Item items = 10;</code>
     * @param array<\Eolymp\Commerce\Order\Item>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eolymp\Commerce\Order\Item::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.commerce.Address billing_address = 40;</code>
     * @return \Eolymp\Commerce\Address|null
     */
    public function getBillingAddress()
    {
        return $this->billing_address;
    }

    public function hasBillingAddress()
    {
        return isset($this->billing_address);
    }

    public function clearBillingAddress()
    {
        unset($this->billing_address);
    }

    /**
     * Generated from protobuf field <code>.eolymp.commerce.Address billing_address = 40;</code>
     * @param \Eolymp\Commerce\Address $var
     * @return $this
     */
    public function setBillingAddress($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Commerce\Address::class);
        $this->billing_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.commerce.Address shipping_address = 41;</code>
     * @return \Eolymp\Commerce\Address|null
     */
    public function getShippingAddress()
    {
        return $this->shipping_address;
    }

    public function hasShippingAddress()
    {
        return isset($this->shipping_address);
    }

    public function clearShippingAddress()
    {
        unset($this->shipping_address);
    }

    /**
     * Generated from protobuf field <code>.eolymp.commerce.Address shipping_address = 41;</code>
     * @param \Eolymp\Commerce\Address $var
     * @return $this
     */
    public function setShippingAddress($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Commerce\Address::class);
        $this->shipping_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool billing_same_as_shipping = 42;</code>
     * @return bool
     */
    public function getBillingSameAsShipping()
    {
        return $this->billing_same_as_shipping;
    }

    /**
     * Generated from protobuf field <code>bool billing_same_as_shipping = 42;</code>
     * @param bool $var
     * @return $this
     */
    public function setBillingSameAsShipping($var)
    {
        GPBUtil::checkBool($var);
        $this->billing_same_as_shipping = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp estimated_shipping_date = 45;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEstimatedShippingDate()
    {
        return $this->estimated_shipping_date;
    }

    public function hasEstimatedShippingDate()
    {
        return isset($this->estimated_shipping_date);
    }

    public function clearEstimatedShippingDate()
    {
        unset($this->estimated_shipping_date);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp estimated_shipping_date = 45;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEstimatedShippingDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->estimated_shipping_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 20;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 total_amount = 21;</code>
     * @return int
     */
    public function getTotalAmount()
    {
        return $this->total_amount;
    }

    /**
     * Generated from protobuf field <code>uint32 total_amount = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->total_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 shipping_amount = 22;</code>
     * @return int
     */
    public function getShippingAmount()
    {
        return $this->shipping_amount;
    }

    /**
     * Generated from protobuf field <code>uint32 shipping_amount = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setShippingAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->shipping_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 discount_amount = 23;</code>
     * @return int
     */
    public function getDiscountAmount()
    {
        return $this->discount_amount;
    }

    /**
     * Generated from protobuf field <code>uint32 discount_amount = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setDiscountAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->discount_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 tax_amount = 24;</code>
     * @return int
     */
    public function getTaxAmount()
    {
        return $this->tax_amount;
    }

    /**
     * Generated from protobuf field <code>uint32 tax_amount = 24;</code>
     * @param int $var
     * @return $this
     */
    public function setTaxAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->tax_amount = $var;

        return $this;
    }

    /**
     * in hundredth of percent, e.g. 755 means 7.55%
     *
     * Generated from protobuf field <code>uint32 tax_rate = 25;</code>
     * @return int
     */
    public function getTaxRate()
    {
        return $this->tax_rate;
    }

    /**
     * in hundredth of percent, e.g. 755 means 7.55%
     *
     * Generated from protobuf field <code>uint32 tax_rate = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setTaxRate($var)
    {
        GPBUtil::checkUint32($var);
        $this->tax_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tax_note = 26;</code>
     * @return string
     */
    public function getTaxNote()
    {
        return $this->tax_note;
    }

    /**
     * Generated from protobuf field <code>string tax_note = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setTaxNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->tax_note = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 grand_total = 30;</code>
     * @return int
     */
    public function getGrandTotal()
    {
        return $this->grand_total;
    }

    /**
     * Generated from protobuf field <code>uint32 grand_total = 30;</code>
     * @param int $var
     * @return $this
     */
    public function setGrandTotal($var)
    {
        GPBUtil::checkUint32($var);
        $this->grand_total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 100;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 100;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 101;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 101;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

}

