<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/commerce/product.proto

namespace Eolymp\Commerce;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Commerce\Product\Translation instead.
     * @deprecated
     */
    class Product_Translation {}
}
class_exists(Product\Translation::class);
@trigger_error('Eolymp\Commerce\Product_Translation is deprecated and will be removed in the next major release. Use Eolymp\Commerce\Product\Translation instead', E_USER_DEPRECATED);

