<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/commerce/subscription_service.proto

namespace Eolymp\Commerce;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.commerce.UpdateSubscriptionInput</code>
 */
class UpdateSubscriptionInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     */
    protected $subscription_id = '';
    /**
     * Generated from protobuf field <code>.eolymp.commerce.Subscription subscription = 2;</code>
     */
    protected $subscription = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $subscription_id
     *     @type \Eolymp\Commerce\Subscription $subscription
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Commerce\SubscriptionService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @return string
     */
    public function getSubscriptionId()
    {
        return $this->subscription_id;
    }

    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubscriptionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->subscription_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eolymp.commerce.Subscription subscription = 2;</code>
     * @return \Eolymp\Commerce\Subscription
     */
    public function getSubscription()
    {
        return $this->subscription;
    }

    /**
     * Generated from protobuf field <code>.eolymp.commerce.Subscription subscription = 2;</code>
     * @param \Eolymp\Commerce\Subscription $var
     * @return $this
     */
    public function setSubscription($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Commerce\Subscription::class);
        $this->subscription = $var;

        return $this;
    }

}

