<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/copilot/chat_service.proto

namespace Eolymp\Copilot\SendMessageInput;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.copilot.SendMessageInput.Approval</code>
 */
class Approval extends \Google\Protobuf\Internal\Message
{
    /**
     * tool call IDs the user approved
     *
     * Generated from protobuf field <code>repeated string allow = 1;</code>
     */
    private $allow;
    /**
     * tool call IDs the user rejected
     *
     * Generated from protobuf field <code>repeated string reject = 2;</code>
     */
    private $reject;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $allow
     *           tool call IDs the user approved
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $reject
     *           tool call IDs the user rejected
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Copilot\ChatService::initOnce();
        parent::__construct($data);
    }

    /**
     * tool call IDs the user approved
     *
     * Generated from protobuf field <code>repeated string allow = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllow()
    {
        return $this->allow;
    }

    /**
     * tool call IDs the user approved
     *
     * Generated from protobuf field <code>repeated string allow = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllow($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->allow = $arr;

        return $this;
    }

    /**
     * tool call IDs the user rejected
     *
     * Generated from protobuf field <code>repeated string reject = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReject()
    {
        return $this->reject;
    }

    /**
     * tool call IDs the user rejected
     *
     * Generated from protobuf field <code>repeated string reject = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReject($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->reject = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Approval::class, \Eolymp\Copilot\SendMessageInput_Approval::class);

