<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/ranker/scoreboard_service.proto

namespace Eolymp\Ranker\UpdateScoreboardColumnInput;

use UnexpectedValueException;

/**
 * Protobuf type <code>eolymp.ranker.UpdateScoreboardColumnInput.Patch</code>
 */
class Patch
{
    /**
     * Generated from protobuf enum <code>ALL = 0;</code>
     */
    const ALL = 0;
    /**
     * Generated from protobuf enum <code>PARENT_ID = 1;</code>
     */
    const PARENT_ID = 1;
    /**
     * Generated from protobuf enum <code>KEY = 2;</code>
     */
    const KEY = 2;
    /**
     * Generated from protobuf enum <code>NAME = 3;</code>
     */
    const NAME = 3;
    /**
     * Generated from protobuf enum <code>SHORT_NAME = 4;</code>
     */
    const SHORT_NAME = 4;
    /**
     * Generated from protobuf enum <code>INDEX = 5;</code>
     */
    const INDEX = 5;
    /**
     * Generated from protobuf enum <code>VISIBLE = 6;</code>
     */
    const VISIBLE = 6;
    /**
     * Generated from protobuf enum <code>FILTERABLE = 7;</code>
     */
    const FILTERABLE = 7;
    /**
     * Generated from protobuf enum <code>SORTABLE = 8;</code>
     */
    const SORTABLE = 8;

    private static $valueToName = [
        self::ALL => 'ALL',
        self::PARENT_ID => 'PARENT_ID',
        self::KEY => 'KEY',
        self::NAME => 'NAME',
        self::SHORT_NAME => 'SHORT_NAME',
        self::INDEX => 'INDEX',
        self::VISIBLE => 'VISIBLE',
        self::FILTERABLE => 'FILTERABLE',
        self::SORTABLE => 'SORTABLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Patch::class, \Eolymp\Ranker\UpdateScoreboardColumnInput_Patch::class);

