<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/l10n/translation.proto

namespace GPBMetadata\Eolymp\L10N;

class Translation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Eolymp\Annotations\Mcp::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDC\x03\x0A\x1Deolymp/l10n/translation.proto\x12\x0Beolymp.l10n\x1A\x1Fgoogle/protobuf/timestamp.proto\"\xD7\x02\x0A\x0BTranslation\x12\x12\x0A\x02id\x18\x01 \x01(\x09B\x06\xA8\xF0\xF0\xE4\x01\x01\x12\x0E\x0A\x06locale\x18\x02 \x01(\x09\x12\x0F\x0A\x07message\x18\x03 \x01(\x09\x127\x0A\x06status\x18\x04 \x01(\x0E2\x1F.eolymp.l10n.Translation.StatusB\x06\xA8\xF0\xF0\xE4\x01\x01\x12\x14\x0A\x0Cneeds_review\x18\x05 \x01(\x08\x12\x1A\x0A\x0Acreated_by\x18\x0A \x01(\x09B\x06\xA8\xF0\xF0\xE4\x01\x01\x126\x0A\x0Acreated_at\x18\x0B \x01(\x0B2\x1A.google.protobuf.TimestampB\x06\xA8\xF0\xF0\xE4\x01\x01\x127\x0A\x0Bapproved_at\x18\x0C \x01(\x0B2\x1A.google.protobuf.TimestampB\x06\xA8\xF0\xF0\xE4\x01\x01\"7\x0A\x06Status\x12\x08\x0A\x04NONE\x10\x00\x12\x0B\x0A\x07PENDING\x10\x01\x12\x0A\x0A\x06ACTIVE\x10\x02\x12\x0A\x0A\x06UNUSED\x10\x04B+Z)github.com/eolymp/go-sdk/eolymp/l10n;l10nb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

