<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/mail/template_service.proto

namespace Eolymp\Mail;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.mail.DescribeTemplateInput</code>
 */
class DescribeTemplateInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string template_id = 1;</code>
     */
    protected $template_id = '';
    /**
     * Generated from protobuf field <code>string locale = 1122;</code>
     */
    protected $locale = '';
    /**
     * Generated from protobuf field <code>repeated .eolymp.mail.Template.Extra.Field extra = 1123;</code>
     */
    private $extra;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $template_id
     *     @type string $locale
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $extra
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Mail\TemplateService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string template_id = 1;</code>
     * @return string
     */
    public function getTemplateId()
    {
        return $this->template_id;
    }

    /**
     * Generated from protobuf field <code>string template_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->template_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string locale = 1122;</code>
     * @return string
     */
    public function getLocale()
    {
        return $this->locale;
    }

    /**
     * Generated from protobuf field <code>string locale = 1122;</code>
     * @param string $var
     * @return $this
     */
    public function setLocale($var)
    {
        GPBUtil::checkString($var, True);
        $this->locale = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.mail.Template.Extra.Field extra = 1123;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.mail.Template.Extra.Field extra = 1123;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtra($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Eolymp\Mail\Template\Extra\Field::class);
        $this->extra = $arr;

        return $this;
    }

}

