<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/automation/condition.proto

namespace Eolymp\Automation\Condition\PBString;

use UnexpectedValueException;

/**
 * Protobuf type <code>eolymp.automation.Condition.String.Operator</code>
 */
class Operator
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_OPERATOR = 0;</code>
     */
    const UNKNOWN_OPERATOR = 0;
    /**
     * Generated from protobuf enum <code>EQUAL = 1;</code>
     */
    const EQUAL = 1;
    /**
     * Generated from protobuf enum <code>NOT_EQUAL = 2;</code>
     */
    const NOT_EQUAL = 2;
    /**
     * Generated from protobuf enum <code>STARTS_WITH = 3;</code>
     */
    const STARTS_WITH = 3;
    /**
     * Generated from protobuf enum <code>ENDS_WITH = 4;</code>
     */
    const ENDS_WITH = 4;
    /**
     * Generated from protobuf enum <code>CONTAINS = 5;</code>
     */
    const CONTAINS = 5;
    /**
     * Generated from protobuf enum <code>NOT_CONTAINS = 6;</code>
     */
    const NOT_CONTAINS = 6;

    private static $valueToName = [
        self::UNKNOWN_OPERATOR => 'UNKNOWN_OPERATOR',
        self::EQUAL => 'EQUAL',
        self::NOT_EQUAL => 'NOT_EQUAL',
        self::STARTS_WITH => 'STARTS_WITH',
        self::ENDS_WITH => 'ENDS_WITH',
        self::CONTAINS => 'CONTAINS',
        self::NOT_CONTAINS => 'NOT_CONTAINS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Operator::class, \Eolymp\Automation\Condition_String_Operator::class);

