<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/automation/rule_service.proto

namespace Eolymp\Automation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.automation.DescribeRuleOutput</code>
 */
class DescribeRuleOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.eolymp.automation.Rule rule = 1;</code>
     */
    protected $rule = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Eolymp\Automation\Rule $rule
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Automation\RuleService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.eolymp.automation.Rule rule = 1;</code>
     * @return \Eolymp\Automation\Rule|null
     */
    public function getRule()
    {
        return $this->rule;
    }

    public function hasRule()
    {
        return isset($this->rule);
    }

    public function clearRule()
    {
        unset($this->rule);
    }

    /**
     * Generated from protobuf field <code>.eolymp.automation.Rule rule = 1;</code>
     * @param \Eolymp\Automation\Rule $var
     * @return $this
     */
    public function setRule($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Automation\Rule::class);
        $this->rule = $var;

        return $this;
    }

}

