<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/automation/rule_service.proto

namespace Eolymp\Automation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.automation.UpdateRuleOutput</code>
 */
class UpdateRuleOutput extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Automation\RuleService::initOnce();
        parent::__construct($data);
    }

}

