<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/typewriter/block.proto

namespace Eolymp\Typewriter;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Typewriter\Block\PBList instead.
     * @deprecated
     */
    class Block_List {}
}
class_exists(Block\PBList::class);
@trigger_error('Eolymp\Typewriter\Block_List is deprecated and will be removed in the next major release. Use Eolymp\Typewriter\Block\PBList instead', E_USER_DEPRECATED);

