<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/typewriter/block.proto

namespace Eolymp\Typewriter;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Typewriter\Block\Embed instead.
     * @deprecated
     */
    class Block_Embed {}
}
class_exists(Block\Embed::class);
@trigger_error('Eolymp\Typewriter\Block_Embed is deprecated and will be removed in the next major release. Use Eolymp\Typewriter\Block\Embed instead', E_USER_DEPRECATED);

