<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/typewriter/typewriter.proto

namespace Eolymp\Typewriter;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Typewriter\ListFragmentsInput\Filter instead.
     * @deprecated
     */
    class ListFragmentsInput_Filter {}
}
class_exists(ListFragmentsInput\Filter::class);
@trigger_error('Eolymp\Typewriter\ListFragmentsInput_Filter is deprecated and will be removed in the next major release. Use Eolymp\Typewriter\ListFragmentsInput\Filter instead', E_USER_DEPRECATED);

