<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/format/problem.proto

namespace Eolymp\Format;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Format\Problem\Script instead.
     * @deprecated
     */
    class Problem_Script {}
}
class_exists(Problem\Script::class);
@trigger_error('Eolymp\Format\Problem_Script is deprecated and will be removed in the next major release. Use Eolymp\Format\Problem\Script instead', E_USER_DEPRECATED);

