<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/format/problem.proto

namespace Eolymp\Format;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Format\Problem\Testset\Scoring instead.
     * @deprecated
     */
    class Problem_Testset_Scoring {}
}
class_exists(Problem\Testset\Scoring::class);
@trigger_error('Eolymp\Format\Problem_Testset_Scoring is deprecated and will be removed in the next major release. Use Eolymp\Format\Problem\Testset\Scoring instead', E_USER_DEPRECATED);

