<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/discussion/post_service.proto

namespace Eolymp\Discussion;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.discussion.CreatePostInput</code>
 */
class CreatePostInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.eolymp.discussion.Post post = 1;</code>
     */
    protected $post = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Eolymp\Discussion\Post $post
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Discussion\PostService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.eolymp.discussion.Post post = 1;</code>
     * @return \Eolymp\Discussion\Post|null
     */
    public function getPost()
    {
        return $this->post;
    }

    public function hasPost()
    {
        return isset($this->post);
    }

    public function clearPost()
    {
        unset($this->post);
    }

    /**
     * Generated from protobuf field <code>.eolymp.discussion.Post post = 1;</code>
     * @param \Eolymp\Discussion\Post $var
     * @return $this
     */
    public function setPost($var)
    {
        GPBUtil::checkMessage($var, \Eolymp\Discussion\Post::class);
        $this->post = $var;

        return $this;
    }

}

