<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/content/discussion_service.proto

namespace Eolymp\Content;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Content\ListMessagesInput\Sortable instead.
     * @deprecated
     */
    class ListMessagesInput_Sortable {}
}
class_exists(ListMessagesInput\Sortable::class);
@trigger_error('Eolymp\Content\ListMessagesInput_Sortable is deprecated and will be removed in the next major release. Use Eolymp\Content\ListMessagesInput\Sortable instead', E_USER_DEPRECATED);

