<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/content/post_service.proto

namespace Eolymp\Content;

if (false) {
    /**
     * This class is deprecated. Use Eolymp\Content\ModeratePostInput\Outcome instead.
     * @deprecated
     */
    class ModeratePostInput_Outcome {}
}
class_exists(ModeratePostInput\Outcome::class);
@trigger_error('Eolymp\Content\ModeratePostInput_Outcome is deprecated and will be removed in the next major release. Use Eolymp\Content\ModeratePostInput\Outcome instead', E_USER_DEPRECATED);

