<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/content/tasks.proto

namespace Eolymp\Content;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TranslateFragmentTask is the payload of the background task which translates a content fragment
 * from the source locale into the target locales.
 *
 * Generated from protobuf message <code>eolymp.content.TranslateFragmentTask</code>
 */
class TranslateFragmentTask extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string fragment_id = 1;</code>
     */
    protected $fragment_id = '';
    /**
     * Generated from protobuf field <code>string source_locale = 2;</code>
     */
    protected $source_locale = '';
    /**
     * Generated from protobuf field <code>repeated string target_locales = 3;</code>
     */
    private $target_locales;
    /**
     * overwrite translations which were edited manually
     *
     * Generated from protobuf field <code>bool override_manual = 4;</code>
     */
    protected $override_manual = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $fragment_id
     *     @type string $source_locale
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $target_locales
     *     @type bool $override_manual
     *           overwrite translations which were edited manually
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Content\Tasks::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string fragment_id = 1;</code>
     * @return string
     */
    public function getFragmentId()
    {
        return $this->fragment_id;
    }

    /**
     * Generated from protobuf field <code>string fragment_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFragmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->fragment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_locale = 2;</code>
     * @return string
     */
    public function getSourceLocale()
    {
        return $this->source_locale;
    }

    /**
     * Generated from protobuf field <code>string source_locale = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceLocale($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_locale = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string target_locales = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTargetLocales()
    {
        return $this->target_locales;
    }

    /**
     * Generated from protobuf field <code>repeated string target_locales = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTargetLocales($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->target_locales = $arr;

        return $this;
    }

    /**
     * overwrite translations which were edited manually
     *
     * Generated from protobuf field <code>bool override_manual = 4;</code>
     * @return bool
     */
    public function getOverrideManual()
    {
        return $this->override_manual;
    }

    /**
     * overwrite translations which were edited manually
     *
     * Generated from protobuf field <code>bool override_manual = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setOverrideManual($var)
    {
        GPBUtil::checkBool($var);
        $this->override_manual = $var;

        return $this;
    }

}

