<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eolymp/commerce/product.proto

namespace GPBMetadata\Eolymp\Commerce;

class Product
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Eolymp\Ecm\Content::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB9\x05\x0A\x1Deolymp/commerce/product.proto\x12\x0Feolymp.commerce\"\xC9\x04\x0A\x07Product\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x0C\x0A\x04name\x18\x02 \x01(\x09\x12(\x0A\x0Bdescription\x18\x03 \x01(\x0B2\x13.eolymp.ecm.Content\x12\x0E\x0A\x06images\x18\x0A \x03(\x09\x12\x14\x0A\x0Cout_of_stock\x18\x1E \x01(\x08\x12\x10\x0A\x08currency\x18\x14 \x01(\x09\x12\x12\x0A\x0Aunit_price\x18\x15 \x01(\x09\x12\x1A\x0A\x12credit_equivalence\x18\x16 \x01(\x09\x126\x0A\x0Aattributes\x18( \x03(\x0B2\".eolymp.commerce.Product.Attribute\x122\x0A\x08variants\x182 \x03(\x0B2 .eolymp.commerce.Product.Variant\x1AR\x0A\x05Extra\"I\x0A\x05Field\x12\x11\x0A\x0DUNKNOWN_FIELD\x10\x00\x12\x15\x0A\x11DESCRIPTION_VALUE\x10\x01\x12\x16\x0A\x12DESCRIPTION_RENDER\x10\x02\x1A'\x0A\x09Attribute\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05label\x18\x02 \x01(\x09\x1A\xA8\x01\x0A\x07Variant\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12<\x0A\x06values\x18\x02 \x03(\x0B2,.eolymp.commerce.Product.Variant.ValuesEntry\x12\x0E\x0A\x06images\x18\x0A \x03(\x09\x12\x14\x0A\x0Cout_of_stock\x18\x1E \x01(\x08\x1A-\x0A\x0BValuesEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01B3Z1github.com/eolymp/go-sdk/eolymp/commerce;commerceb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

