<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eolymp/judge/scoreboard_service.proto

namespace Eolymp\Judge\ListScoreboardRowsInput;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eolymp.judge.ListScoreboardRowsInput.ExpressionAttribute</code>
 */
class ExpressionAttribute extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string attribute_key = 1;</code>
     */
    protected $attribute_key = '';
    /**
     * Generated from protobuf field <code>repeated .eolymp.wellknown.ExpressionInt number = 10;</code>
     */
    private $number;
    /**
     * Generated from protobuf field <code>repeated .eolymp.wellknown.ExpressionString string = 11;</code>
     */
    private $string;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $attribute_key
     *     @type array<\Eolymp\Wellknown\ExpressionInt>|\Google\Protobuf\Internal\RepeatedField $number
     *     @type array<\Eolymp\Wellknown\ExpressionString>|\Google\Protobuf\Internal\RepeatedField $string
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eolymp\Judge\ScoreboardService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string attribute_key = 1;</code>
     * @return string
     */
    public function getAttributeKey()
    {
        return $this->attribute_key;
    }

    /**
     * Generated from protobuf field <code>string attribute_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAttributeKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->attribute_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.wellknown.ExpressionInt number = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.wellknown.ExpressionInt number = 10;</code>
     * @param array<\Eolymp\Wellknown\ExpressionInt>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNumber($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eolymp\Wellknown\ExpressionInt::class);
        $this->number = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.wellknown.ExpressionString string = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getString()
    {
        return $this->string;
    }

    /**
     * Generated from protobuf field <code>repeated .eolymp.wellknown.ExpressionString string = 11;</code>
     * @param array<\Eolymp\Wellknown\ExpressionString>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setString($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eolymp\Wellknown\ExpressionString::class);
        $this->string = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ExpressionAttribute::class, \Eolymp\Judge\ListScoreboardRowsInput_ExpressionAttribute::class);

